kernelci/kernelci-pipeline

src/trigger.py

Fix the --poll-period help in trigger.py and add missing import time.
Fixes: 1f49cd92b848 ("src/trigger.py: add script to detect new revisions")

src/trigger.py: fix --poll-period

---

src/trigger.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/3
src/trigger.py: add get_node_by_commit_id
src/trigger.py: get latest git commit and use it to get node
src/trigger.py: send revision node with empty describe
src/trigger.py: define revision dict and remove unnecessary code

Push git commit with trigger.py

---

src/trigger.py

Move get_nodes_by_commit_hash method to kernelci.data.kernelci_api.py
in kernelci-core.

src/trigger.py: use kernelci.data.get_nodes_by_commit_hash

---

config/kernelci.conf
src/trigger.py

Drop the now unused `--output` and `--kdir` command line arguments since there is no local git checkout any more. Update `kernelci.conf` accordingly.

src/trigger.py: drop --output and --kdir

---

config/kernelci.conf
docker-compose.yaml
src/tarball.py

Add `tarball.py` to listen to `checkout` Node events without a status, then update a Git repo, push a source tarball and update the Node with `describe` string and status (`True` if everything passed).  Update config files accordingly.
Depends on https://github.com/kernelci/kernelci-api/pull/106

Add tarball client

---

docker/Dockerfile

Pick a fixed revision from the kernelci-core main branch as there is
no released version tag yet with all the changes required for
kernelci-api.  This will ensure the Docker image gets rebuilt whenever
the revision is changed in the file.
The new kernelci-core revision being picked is:
6c277bec689d kernelci/data/kernelci_api: add KernelCI_API.get_nodes_by_commit_hash

docker/Dockerfile: use kernelci-core revision from main branch

---

config/kernelci.conf
config/reports/test-report.jinja2
docker-compose.yaml
src/test_report.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/11
Add client and template to generate test report 
docker-compose.yaml: add 'test_report' service 
config/kernelci.conf: add configuration for 'test_report'

Generate test report

---

config/pipeline.yaml

Add build configurations for the KernelCI staging kernel branches so
the pipeline can be run on staging periodically.

config/pipeline.yaml: add KernelCI staging branches

---

docker/Dockerfile

The kernelci-core revision is likely to be changing often until things
settle down.  Move the kcidb line before it so that the kcidb layer
doesn't need to be rebuilt every time the kernelci-core revision
changes in the file.

docker/Dockerfile: move kcidb before kernelci-core

---

config/scripts/base-python.jinja2
src/notifier.py
src/runner.py
src/send_kcidb.py
src/tarball.py
src/test_report.py

Node.status is now defined as Enum type, with 'pending'
as its default value. Hence, modified condition to
check status in client scripts.

Reflect Node.status field schema in client scripts

---

docker/Dockerfile
src/runner.py
src/tarball.py

Use the new method from kernelci-core subscribe_node_channel() with filters to only receive nodes objects that match a particular set of criteria and simplify the logic in the client code accordingly.

Use event filters in clients

---

src/trigger.py

Add a --force command line argument to always send a checkout node
even if the revision is already in the database.  This is particularly
useful for staging and development, or to re-run a pipeline when
something failed.  It will however create a duplicate checkout node.

src/trigger.py: add --force to always send checkout node

---

src/runner.py

Populate the db_config_yaml template parameter directly rather than
relying on the lab object to do it.  This is to better separate the
logic and make .generate() limit itself to generating the job
definition strictly only with the provided parameters.

src/runner.py: populate db_config_yaml directly

---

src/runner.py

Fix the --verbose argument to be optional rather than required.
Fixes: c712aedfe8f8 ("src/runner.py: add --verbose argument")

src/runner.py: make --verbose an optional argument

---

src/notifier.py
src/runner.py
src/send_kcidb.py
src/tarball.py
src/test_report.py
src/trigger.py

Update all the client scripts to use kernleci.db as it is being renamed from kernelci.data in kernelci-core.

src/*.py: use kernelci.db

---

config/pipeline.yaml

Add the config_path attribute to the shell "lab" so that the scripts
templates installed from the kernelci Pyhon package can be found by
runner.py.
Depends on https://github.com/kernelci/kernelci-core/pull/1142

config/pipeline.yaml: add config_path to shell

---

config/kernelci.conf

Add entry in kernelci.conf for the staging.kernelci.org db config.
This can be used by anyone with an API token.

config/kernelci.conf: add staging db config

---

src/runner.py

Load Jinja2 templates installed from the kernelci Python package.
These include the base templates for scripts and Kubernetes job
definitions.

src/runner.py: load package templates

---

config/kubernetes/check-describe.jinja2

Add config/kubernetes/check-describe.jinja2 template which inherits
from the base-k8s-python.jinja2 template from kernelci-core.  This is
an intermediate step towards merging it with the
scripts/check-describe.jinja2 template which would inherit a different
base depending on the runtime environment (local shell or Kubernetes
etc.).

config/kubernetes: add check-describe.jinja2

---

docker-compose.yaml
src/runner.py

Split the runner.py script into a "loop" command to listen to Pub/Sub
events and a "run" command to only run with a single checkout node.
Update docker-compose.yaml accordingly.
Depends on #58

T35140 runner loop

---

src/runner.py

As the "run" command is meant to be used interactively on the command
line rather than as a standalone service, print an error message and
exit cleanly when an exception is raised.
Depends on #59

T35140 runner exceptions

---

docker-compose.yaml

Add a SETTINGS argument in docker-compose to be able to specify the
kernelci.conf file to use.  The default remains the same
config/kernelci.conf one.
For example:
SETTINGS=/home/kernelci/config/kernelci-local.conf docker-compose run runner

docker-compose.yaml: add SETTINGS argument to use alternative file

---

config/kernelci.conf
docker-compose.yaml

Need to mount empty directory for linux source to have `kernelci` permission instead of `root` within tarball container.
Modify `kernelci.conf` for the same.

T35745 Fix permission issues with linux repository creation

---

config/kubernetes/check-describe.jinja2
config/scripts/check-describe.jinja2

Align the scripts/check-describe.jinja2 template with the one in
kubernetes as an intermediate step to merge them together.  The only
difference left is the name of the base template.
Depends on https://github.com/kernelci/kernelci-core/pull/1201

config/scripts: align check-describe template with kubernetes

---

config/pipeline.yaml
src/runner.py

Stop using the `config_path` attribute which is now deprecated and update the templates path to use the `runtime` directory.
Depends on https://github.com/kernelci/kernelci-core/pull/1317 and https://github.com/kernelci/kernelci-core/pull/1301

Update template paths to use runtime directory

---

config/pipeline.yaml
src/runner.py

Drop the `_python` suffix in the device type names as the language being used is now defined in the test templates.

Drop python suffix in device types

---

src/runner.py

Add the --plan argument to the runner loop command to be able to
specify the test plan to run rather than having it hard-coded to
"kver".

src/runner.py: add loop --plan argument

---

docker-compose.yaml

Depends on #83, #84, #88
Set default plan names with kver for runner and kunit for runner-k8s.
This is now required as the --plan argument is being added to the
runner.py loop command.

docker-compose.yaml: set default plans for runner services

---

config/runtime/kver.jinja2

Drop unused import as the requests package is imported in the
python.jinja2 base template already.

kver.jinja2: drop duplicate requests import

---

config/pipeline.yaml
src/runner.py

Add the runtime_image template parameter currently only used by
base/kubernetes.jinja2 to specify the Docker image to use when running
the test plan.

runner.py: add runtime_image template parameter

---

src/runner.py
src/trigger.py

As `get_nodes` API can now be used with required
node attributes (in this case commit HASH) , used it instead
of `get_nodes_by_commit_hash`.

T35078 src: use `get_nodes` to get nodes from commit

---

src/test_report.py

As `get_nodes` can be used to get all child nodes
by providing parent id using attributes, need
to replace `get_child_nodes_from_parent` with it.

T35078 src/test_report: use `get_nodes` to get child nodes from parent

---

src/fstests/README.md

Add a readme about the Proof-of-Concept project for running fstests in
KernelCI in a new sub-directory src/fstests.
Fixes #97

src/fstests: add README.md about PoC

---

config/kernelci.conf
config/logger.conf
docker-compose.yaml
src/set_timeout.py

Depends on https://github.com/kernelci/kernelci-core/pull/1265
Add a client script that periodically checks if node status is pending and changes its status to timeout if the maximum wait time is over.

T35078 Client script to set node status to timeout

---

src/fstests/runner.py

Add a new class to handle fstests on Kernel CI. This first commit is listering for tarball events and print a message if it receives any tarball.
Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

src/fstests: listening for new tarball events

---

src/fstests/README.md
src/fstests/requirements.txt
src/fstests/runner.py

- Add a method to check if kvm-xfstests is available in the client environment.
- Include kernelci library as a requirement.

Fstests subprocess kvm xfstests

---

config/pipeline.yaml

Fix a typo in the kver image name used for Docker.
Fixes: 3c139d4544d2 ("config/pipeline.yaml: add image attribute for kver")

config/pipeline.yaml: fix typo in kver Docker image name

---

src/complete_hack.py
src/notifier.py
src/runner.py
src/send_kcidb.py
src/set_timeout.py
src/tarball.py
src/test_report.py
src/trigger.py

When an unexpected exception occurs during a loop, catch it and log
the call stack as when it's not handled rather than silencing it with
the `finally` clause.  This helps with debugging to find where errors
are coming from.

src: dump call stack when catching unexpected exception

---

config/kernelci.conf
config/pipeline.yaml
config/runtime/fstests.jinja2
src/fstests/runner.py

- Add a jinja2 template for fstests.
- Add a fstests test plan.
- Update the run function to run to generate a job and run it using shell lab.
- Drop the code used to run `kvm-xfstests` as a subprocess.

Add kvm xfstest conf and template

---

config/runtime/kunit.jinja2

Parse the output results.json file after running KUnit and submit the
results recursively to the API with child nodes for test cases within
sub-groups.
Depends on https://github.com/kernelci/kernelci-core/pull/1368

config/runtime: parse and submit KUnit results

---

config/runtime/kver.jinja2

Update the kver test plan template to use the new Job() class.
Depends on https://github.com/kernelci/kernelci-core/pull/1368

config/runtime: update kver to use Job() class

---

src/runner.py

Also print the stack trace when catching an expected exception with
the 'run' command, not just 'loop'.  The 'run' command is mostly used
for debugging and development so having details about exceptions is
very useful.
Fixes: 75b9c16b8f26 ("src: dump call stack when catching unexpected exception")

src/runner.py: also print stack in run command

---

src/complete_hack.py

Extend the arbitrary timeout in complete_hack.py to 10 minutes to
avoid marking the parent node "complete" too early.

src/complete_hack.py: extend timeout to 10 minutes

---

config/runtime/kver.jinja2

Rather than passing True or False, pass the actual result string to
set in the node in the kver test template.

config/runtime: set result string in kver.jinja2

---

config/runtime/kunit.jinja2
src/runner.py
src/tarball.py
src/trigger.py

Add the `Node.group` and `Node.path` attributes when submitting nodes where applicable.
Depends on https://github.com/kernelci/kernelci-api/pull/167 and https://github.com/kernelci/kernelci-api/pull/168

Add group and path attributes

---

src/complete_hack.py

Update complete_hack.py with the new Node state names, essentially
"done" instead of "complete'.  This script is still a complete hack.

src/complete_hack: use new Node state names

---

config/kernelci.conf
src/fstests/fstests.jinja2
src/fstests/fstests.kernelci.conf
src/fstests/runner.py

- add a step to get fstests results.xml file and copy it to the kernel source directory.
- parse fstests XML result file into a JSON containing the node structure to be submitted.
- small design improviments

src/fstests: parse fstests results

---

src/tarball.py

Use the new Node state names and only set the tarball artifact URL in the tarball node, not the checkout node.
Depends on #112

tarball.py: update state names and put tarball URL in tarball node

---

config/runtime/kunit.jinja2

Use the new `Database.submit_results()` method to submit a full hierarchy of test results in a single HTTP request.
Depends on https://github.com/kernelci/kernelci-core/pull/1408 and #112

KUnit: submit full results hierarchy at once

---

config/reports/test-report.jinja2
src/test_report.py

Add data from test group results to email reports.
Depends on #117 
Sample email report:
```
mainline/master v5.19-14184-g69dac8e431af: 2 runs 1 failures
Summary
=======
Tree:     mainline
Branch:   master
Describe: v5.19-14184-g69dac8e431af
URL:      https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
SHA1:     69dac8e431af26173ca0a1ebc87054e01c585bcc
Name            | Result   | Total    | Failures
----------------+----------+----------+---------
kver            | pass     |        0 |        0
kunit           | fail     |      234 |        1
Failing tests
=============
kunit
-----
* property-entry.pe_test_uints
```

Add test group data in email reports

---

src/runner.py

The keywoard argument templates_path has been renamed to templates_paths as it can now be either a string with a single path or a list of paths.

src/runner.py: pass templates_paths argument to .generate()

---

src/test_report.py

Drop a redundant log message showing the email contents in _create_email() as it's already done in the main loop.

src/test_report.py: drop redundant report log message

---

src/fstests/runner.py

Now the tarball and checkout nodes have been merged into one, there's no tarball node but only checkout node and it contains the tarball URL when it's in available state.
Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

src/fstests: update pub/sub configuration

---

config/reports/test-report.jinja2
src/test_report.py

Use `Database.count_nodes` method to request `/count` endpoint to get node group statistics.

T37834 src/test_report: use `count_nodes` to get group stats

---

config/kernelci.conf
src/trigger.py

Rather than specifying a single build config, update the trigger service to iterate over all the build configs defined in the YAML configuration.  Adjust log messages accordingly and fix exception handling as we can now run this in a loop with the `--poll` argument and not the `--force` argument.

Trigger all build configs

---

src/timeout.py

Depends on https://github.com/kernelci/kernelci-api/pull/184
As `Node.timeout` field directly holds the expiry timestamp now, no need to calculate it anymore in `_update_closing_node`.

T37965 src/timeout: drop expiry timestamp calculation

---

src/fstests/fstests.jinja2
src/notifier.py
src/timeout.py

- fstests: update node result of skipped tests
- src/notifier: add `skip` and `incomplete` results
- src/timeout: set timed out node result
Implement method `_set_node_result` to set node result of timed-out nodes. If the node is in 'running' state, set the
node result to 'incomplete'.
When the timed-out node is not in 'running' state, set the node result to 'fail' if one of the child nodes failed. Otherwise, set the result to 'pass'.

T36848 Set `Node.result` of timed out nodes and skipped tests

---

docker-compose.yaml
src/send_kcidb.py

src/send_kcidb: subscribe to node channel with filters
Subscribe node channel to get completed checkout nodes with filters instead of verifying each node.
Also, need to update the filters as per the new node schema.

T38987 send_kcidb: update node filters

---

docker-compose.yaml

docker-compose: mount volume for kcidb  submission credentials
Need to mount `/data/kcidb` volume containing google application credentials file.

T38987 send_kcidb: mount volume for submission credentials file

---

src/trigger.py

The Context object was in a previous implementation which got reverted.  Fix this by returning a plain dictionary instead.
Fixes: ae0529889d08 ("src/trigger.py: use args in context rather than in constructor")

src/trigger.py: drop Context object

---

config/kernelci.conf
src/trigger.py

Add `--startup-delay` and `--build-configs` command line arguments to `trigger.py`.  These are useful in practice respectully to wait for a short amount of time (heuristics) for all the services to be up and running, and to limit the build configurations to monitor.
Also add a default startup delay of 3 seconds for the trigger script (see commit description for more details).
Depends on #179

Add --startup-delay and --build-configs to trigger.py

---

src/base.py
src/logger.py
src/notifier.py
src/runner.py
src/tarball.py
src/test_report.py
src/timeout.py
src/trigger.py

Add `Service.log_*()` helper methods to simplify the syntax for log messages.  Update all services using the `Service` class accordingly.
Update `test_report.py` and `timeout.py` to use the `Service` class and align them with the other services.
Depends on #177

Add Service.log_* helpers and align test_report and timeout

---

src/test_report.py

Make the --smtp-host (and --smtp-port) arguments optional so the service can be run without them to just print the email report text on stdout.  This is particularly useful during development to have local reports without spamming any email.

src/test_report.py: make the SMTP args optional

---

src/trigger.py

Fix the case where no --build-configs optional argument is provided using an empty string instead of None which can't be split.
Fixes: 81387ab4786d ("src/trigger.py: add --build-configs optional argument")

src/trigger.py: fix issue with empty --build-configs

---

config/logger.conf
docker-compose.yaml
src/timeout.py
src/trigger.py

Rework the implementation of the timeout / holdoff / closing services to address the following issues:
* retrieve only the nodes in the state relevant to the code, e.g. nodes in the 'done' state aren't needed for the timeout service
* split the implementation into different classes which run in different services to have better separation of the logic: Timeout for the main timeout, Holdoff for the holdoff timeout and Closing for nodes waiting in the Closing state
* avoid resubmitting the same nodes multiple times by first creating a set of nodes to update and then send them to the API
* work out the shortest time to sleep until next timeout / holdoff to allow longer polling periods and update nodes closer to the timeout / holdoff time

Rework the timeout service(s)

---

src/job.py
src/runner.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/183
`Job` class has been implemented in order to separate logic for generating and scheduling various jobs (e.g. tests and builds) from `Runner`.
Instantiate it in the `Runner` and use it in `RunnerLoop` and `RunnerSingleJob` classes.

T39644 Implement job class

---

src/tarball.py
src/timeout.py

PUT node request can result in HTTPException if the node is not found or API detects an invalid state transition.
Need to handle the potential exceptions from `submit` method in `tarball` and `timeout` scripts.

T38454 Handle exceptions when updating nodes

---

src/timeout.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/192
- src/timeout: use `timeout__lt` filter to get timed-out nodes
- src/timeout: use `holdoff__lt` filter to get nodes with lapsed holdoff
- src/timeout: drop logic to check pending and available nodes
- src/timeout: add `_setup` method to `TimeoutService`

T39465 Optimize timeout service with comparison operators

---

config/kernelci.conf
config/pipeline.yaml
src/base.py
src/job.py
src/notifier.py
src/regression_tracker.py
src/runner.py
src/send_kcidb.py
src/tarball.py
src/test_report.py
src/timeout.py
src/trigger.py

Replace the now-deprecated db_config with the new api_config which is pending to be merged in kernelci-core with https://github.com/kernelci/kernelci-core/pull/1650
Update all the services accordingly.  This is to start transitioning away from the old Database abstraction layer class in kernelci-core into supporting only the KernelCI API.

Use the new api_config in all services

---

src/timeout.py

Fix some pylint errors in timeout.py to drop unused imports and avoid reusing variable names in nested scopes.

src/timeout.py: fix some pylint errors

---

config/pipeline.yaml
docker-compose.yaml
src/job.py
src/runner.py

Update the pipeline YAML configuration and `runner.py` to use the new `runtimes` configuration.
Depends on https://github.com/kernelci/kernelci-core/pull/1737
Fixes #207

Use runtime configuration

---

config/kernelci.conf
config/pipeline.yaml
src/tarball.py

Use the new `kernelci.storage` package in `tarball.py` instead of hard-coding SSH commands.

tarball: use new `kernelci.storage` package

---

src/job.py
src/runner.py

Update src/runner.py and src/job.py to use kernelci.runtime rather than kernelci.lab.
Fixes #207

src/{runner,job}.py: use kernelci.runtime

---

src/base.py

Use the new kernelci.api.get_api() loader to get an API object rather than the kernelci.db one which is now deprecated.

src/base.py: use kernelci.api.get_api()

---

config/runtime/kunit.jinja2

Update the `kunit.jinja2` job template to use the new `API` and `APIHelper` classes.  Also improve how the results are sent by splitting the job into 3 steps: `config`, `build` and `exec`.  This is to avoid losing results when e.g. the build fails.

Update `kunit.jinaj2` to use new API and split job in 3 steps

---

src/timeout.py

Fix the below import error for `from .base import Service` in timeout service:
`ImportError: attempted relative import with no known parent package`.

src/timeout: fix `base.Service` import

---

config/kernelci.conf
src/job.py
src/runner.py

Use `--storage-config` in the runner service to generate jobs that can upload artifacts to storage.

Use storage config in runner service

---

docker-compose.yaml
src/runner.py

As a temporary measure until the YAML configuration can provide a full description of all the jobs to run, rework the `runner.py loop --plan` argument as `--plans` to include a number of test plans and iterate over them when receiving a checkout node.  Update `docker-compose.yaml` accordingly with `kunit kunit-x86_64` for the `runner-k8s` service to run KUnit both on the default UML architecture and on `x86_64`.

Run `kunit` and `kunit-x86_64`  in Kubernetes

---

src/runner.py

Fix the "Device type not found" error message which was missing the 'f' to make it a formatted string.
Fixes: 585a282e338b ("src/runner.py: use logging helpers")

src/runner.py: fix error message format

---

src/test_report.py

Add a [STAGING] prefix in the email report subject to make it clear this is coming from a staging run.  It also helps find the new API & Pipeline reports in the kernelci-staging-results@groups.io archives or with email filters.

src/test_report.py: add [STAGING] prefix in subject

---

config/runtime/kver.jinja2

Use the argument already passed to the Job constructor to store the revision data rather than rely on the global REVISION variable.
This is to follow the idea that the job object should only be accessing its own attributes rather than implicitly depend on global variables set by the template.
Fixes: d6de4f40791e ("config/runtime: update kver to use Job() class")

config/runtime: kver: store revision in Job object

---

src/base.py

Look for the KCI_API_TOKEN environment variable rather than API_TOKEN to align with kernelci-core.
This is to follow a convention of having a KCI_ prefix for all the KernelCI environment variables to avoid name clashes.

src/base.py: use KCI_API_TOKEN environment variable

---

src/send_kcidb.py

Fix below error as the method renamed to `receive_event_node` as per the `APIHelper` implementation.
`AttributeError: 'APIHelper' object has no attribute 'receive_node_event'`

src/send_kcidb: fix `_run` with `APIHelper`

---

src/regression_tracker.py

Fix below error as the method renamed to `receive_event_node` as per the `APIHelper` implementation.
`AttributeError: 'APIHelper' object has no attribute 'receive_node_event'

src/regression_tracker: fix `_run` with `APIHelper`

---

src/job.py
src/runner.py

Rework the runner service to use the new APIHelper.create_job_node() and related kernelci.runtime.Job class to align with the "kci job" tool.

Runtime job

---

config/pipeline.yaml

Add a docker runtime entry in pipeline.yaml even though the volumes would most likely need to be adjusted with the absolute paths on the host, which depends on the local deployment.  So this is more for documentation purposes at the moment.

config/pipeline.yaml: add default docker runtime

---

config/runtime/kbuild.jinja2

Fix a typo where the result was set to 'false' instead of 'fail' when a build step fails.
Fixes: 7d8049dab11b ("config/runtime: kbuild: add basic template for x86_64_defconfig")

config/runtime: kbuild: fix 'fail' result

---

config/pipeline.yaml

Move the legacy configuration data to a separate section at the end of the file.  This is still used by the trigger service to know which kernel repositories and branches to monitor.  The build environment and build variants aren't actually used but are still needed to load the build configurations.

config/pipeline.yaml: move legacy data to separate section

---

docker-compose-kcidb.yaml
docker-compose.yaml

Move the kcidb bridge service to a separate docker-compose-kcidb.yaml file so it can be run only when required by the user.  It also avoid building the Docker image for it when just doing the default "docker-compose build".

docker-compose-kcidb.yaml: add separate file with kcidb bridge

---

src/notifier.py

Use the data directly available in the event now that it contains some generic fields about the node object.

src/notifier.py: use data directly in event

---

src/regression_tracker.py
src/runner.py
src/send_kcidb.py
src/test_report.py
src/timeout.py

Changes due to https://github.com/kernelci/kernelci-api/pull/254
Now the API will send responses with field names and not with the alias, update `Node._id` to `Node.id` in all the services.

T41945 src: update `Node._id` field

---

config/runtime/kunit.jinja2

Always parse the JSON results file if it's present, regardless of the status of the 'exec' step.  If any test case failed, the result will be "fail" but the data in the JSON file will still be present.
Fixes: 8015b47b18f0 ("config/runtime/kunit.jinja2: rework with separate steps")

config/runtime: kunit: parse JSON results if the file is present

---

src/runner.py

Drop the RunnerLoop class which is now redundant as it's the only child class of Runner.  This simplifies the code and was made possible by the `kci` command line tool which can be used instead to run single jobs manually.

runner: drop RunnerLoop class

---

src/lava_callback.py

Rather than using a hard-coded API config and loading the API token from the environment, get the API config name from the job's metadata and the token from the HTTP Authorization header sent by lava.

Get API config and token from callback data

---

src/notifier.py

Correct command line program name argument from `runner` to `notifier` for `kernelci.cli.parse_opts` method. The method is used to get `Options` object with command line arguments and user settings.

src/notifier: fix program name in `parse_opts`

---

config/runtime/kbuild.jinja2
config/runtime/kunit.jinja2

The NODE_ID global variable has been removed so adjust the kbuild and kunit templates accordingly to use the NODE object instead.

config/runtime: use NODE in kbuild and kunit

---

docker-compose-lava.yaml
src/lava_callback.py

Parse the job log from the callback data into a plain text file and upload it to storage.
This partly includes some clean-up as a side-effect since the callback service is still very new.  If required the changes could be broken down into separate commits.
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/214

Parse and upload LAVA job log as plain text

---

config/pipeline.yaml

Use the new base URL for the staging storage which allows plaintext HTTP as well as HTTPS (part of the regular staging storage Nginx setup).

config/pipeline.yaml: use new base_url for staging storage

---

config/pipeline.yaml

Update the YAML pipeline config to use event attributes in the scheduler configuration rather than the job run_on attributes.
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/221

config/pipeline.yaml: update to use scheduler events

---

config/kernelci.toml

As the syntax for TOML settings file has been switched from using `":"` to dotted keys for child section of components like database and storage, use the new syntax in the settings file.

config/kernelci.toml: use dotted keys

---

docker-compose-kcidb.yaml
docker-compose.yaml

Rename the SETTINGS environment variable to KCI_SETTINGS and follow the convention of having a KCI_ prefix for all KernelCI-related environment variables.

docker-compose{-kcidb}.yaml: use KCI_SETTINGS env variable

---

src/test_report.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/273
Provided default value `25` for `smtp_port` command line option takes precedence over TOML setting for it.
This is causing SMTP connection errors and emails are not working.
Remove the default value to fix it.

src/test_report: remove default value for `smtp_port`

---

src/test_report.py

As the API design has been involved over time, we have eliminated `incomplete` from the set of possible values for `Node.result` field.
Optimize the method to get reports accordingly.
Also, remove the unnecessary parenthesis from a line.

src/test_report: optimize `TestReport._get_report` method

---

config/pipeline.yaml

Add a storage-azure storage config entry to use Azure Files with the Azure Storage account created for staging.  This includes a read-only token valid until 2123.
Fixes https://github.com/kernelci/kernelci-api/issues/308

config/pipeline.yaml: add staging-azure storage config

---

src/lava_callback.py

Replace the hard-coded 'config/pipeline.yaml' path to the YAML config file with the value found in the TOML settings file.  Keep using 'config/pipeline.yaml' by default if it's not defined in the settings file.

lava: look up yaml_config in settings

---

config/kernelci.toml
src/kernelci_pipeline/email_sender.py
src/test_report.py

To keep the settings in standard way, remove environment variables for email sender and recipient and convert them to command line arguments.

Convert email configs .env variables to TOML settings

---

src/notifier.py

Print the events log directly on stdout and add titles for the columns to improve readability.

Improve events log format

---

docker-compose.yaml
src/monitor.py

This service is to monitor the API Pub/Sub events rather than sending
notifications which is more what the email report service does.  As
such, rename it from notifier to monitor.
Depends on #300

src/monitor.py: rename from notifier

---

config/pipeline.yaml

Add an API config entry in pipeline.yaml for the Early Access instance deployed in AKS.

config/pipeline.yaml: add early access API entry

---

docker/pipeline/Dockerfile.production
docker/pipeline/kernelci.toml

Add Dockerfile.production to create a kernelci/pipeline Docker image suitable for production deployments in AKS.

kube/aks: add Dockerfile.production

---

config/logger.conf
config/pipeline.yaml
docker-compose.yaml
src/scheduler.py

Rename "runner" to "scheduler" as this pipeline stage is really about scheduling jobs rather than running them.  Also it uses the scheduler YAML config so it's a much better match for what it's doing.
Having descriptive names makes it easier to maintain the code and produce meaningful documentation.

src/scheduler.py: rename from runner

---

config/pipeline.yaml

Add a early-access-azure storage entry to be able to use the AzureFile storage under a different share name for early-access and keep it separate from staging or individual users.

config/pipeline.yaml: add early-access-azure storage

---

config/kernelci.toml

Fix the name of the scheduler section which needs to be renamed from runner.
Fixes: 004e9df2fdd8 ("src/scheduler.py: rename from runner")

config/kernelci.toml: rename runner section to scheduler

---

kube/aks/monitor.yaml

Add monitor.yaml to deploy the monitor in AKS.
This is not strictly speaking a service in Kubernetes terminology as
it doesn't expose any ports and it's only a Pod.  It is kind of a
service as far as the pipeline is concerned.

kube/aks: add monitor.yaml to create the monitor pod

---

kube/aks/kernelci.toml
kube/aks/monitor.yaml
kube/aks/trigger.yaml

Add trigger.yaml to deploy the trigger pipeline step.  Update
kernelci.toml accordingly to monitor the mainline tree every hour.
Depends on #304

kube/aks: add trigger.yaml

---

docker/pipeline/Dockerfile.production

Change the base image for kernelci/pipeline to be
kernelci/k8s:kernelci rather than kernelci/kernelci.  This is required to include all the Kubernetes packages which are needed to run scheduler-k8s.
We could have different images e.g. kernelci/pipeline:k8s instead but that would mean more Dockerfile template rework, so this could be done as a follow-up improvement to optimise Docker images.

docker/pipeline: base Dockerfile.production on k8s:kernelci

---

kube/aks/kernelci.toml
kube/aks/tarball.yaml

Add tarball.yaml to create the pod running the tarball.py script.
This relies on the AzureFiles storage credentials to be stored in
kernelci.toml which is done via a Kubernetes secret passed in the
environment and stored in the file in an initContainer.  It's using a
copy of the file from the git repository in the ephemeral data volume
which is also used to create the source tarballs.
Some other initContainers are also pre-populating a linux git clone
with tags to speed things up when receiving the first events about new
checkouts.  This could be improved with a full git mirror on a
persistent volume.

kube/aks: add tarball.yaml to create tarball pod

---

kube/aks/kernelci.toml
kube/aks/scheduler-k8s.yaml

Add scheduler-k8s to run a scheduler pod which can submit jobs in
Kubernetes (kbuild, kunit...).  This relies on a Kubernetes secret
with a tarball containing the credentials to access the clusters.
Update kernelci.toml accordingly with a scheduler section.

kube/aks: add scheduler-k8s.yaml to create the k8s scheduler pod

---

kube/aks/timeout.yaml

Add timeout.yaml to create the timeout, holdoff and closing pods.

kube/aks: add timeout.yaml to create the timeout pods

---

kube/aks/scheduler-lava.yaml

Add scheduler-lava.yaml to create the pod with the scheduler for LAVA jobs, currently only to be run in the lava-collabora runtime.

kube/aks: add scheduler-lava.yaml to create the LAVA scheduler

---

src/test_report.py

Fix below error when `test_report` service is run
for a single node ID.
```
kernelci-pipeline-test_report | 09/11/2023 07:01:53 AM UTC [ERROR] Traceback (most recent call last):
kernelci-pipeline-test_report |   File "/home/kernelci/pipeline/base.py", line 68, in run
kernelci-pipeline-test_report |     context = self._setup(args)
kernelci-pipeline-test_report |   File "/home/kernelci/pipeline/test_report.py", line 142, in _setup
kernelci-pipeline-test_report |     'root_node': self._api.get_node(args.node_id),
kernelci-pipeline-test_report | AttributeError: 'NoneType' object has no attribute 'node_id'
kernelci-pipeline-test_report |
kernelci-pipeline-test_report exited with code 1
```
The error is due to missing command-line arguments that are not being sent to `Service.run` method from …

src/test_report: fix command handlers of test report

---

config/kernelci.toml
src/trigger.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/319
At the moment, timeout for `checkout` node has been calculated statically in the `trigger` service.
Make it configurable by adding optional command line arguments. Add default timeout configuration values in settings file.

src/trigger: make checkout node timeout configurable

---

config/reports/test-report.jinja2
src/test_report.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/279
Group test results based on `Node.group` rather than parent nodes.
Now the report for checkout node `64b799cede9c1b9fa5d3fe58` looks like this:
```
kernelci-pipeline-test_report | [STAGING] kernelci/staging-stable staging-stable-20230719.0: 4 runs 1 failures
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report | Summary
kernelci-pipeline-test_report | =======
kernelci-pipeline-test_report | 
kernelci-pipeline-test_report | Tree:     kernelci
kernelci-pipeline-test_report | Branch:   staging-stable
kernelci-pipeline-test_report | Describe: staging-stable-20230719.0
kernelci-pipeline-test_report | URL:      https://github.com/kernelci/linux.git
kernelci-pipeline-test_report | SHA1: …
```

Fix results in test report

---

src/fstests/runner.py
src/monitor.py
src/regression_tracker.py
src/scheduler.py
src/send_kcidb.py
src/tarball.py
src/test_report.py
src/timeout.py
src/trigger.py

The kernelci.cli module is now being moved to kernelci.legacy.cli so we can have the new implementation in kernelci.cli instead.  Update all the pipeline services accordingly.

src: use kernelci.legacy.cli

---

src/base.py
src/lava_callback.py

The 'api_configs' YAML entry has been renamed to 'api' so update the pipeline code accordingly.

src: use 'api' instead of 'api_configs' in YAML

---

config/pipeline.yaml

The YAML configuration is being finalised and api_configs is now renamed to api.  Update pipeline.yaml accordingly.

config/pipeline.yaml: replace api_configs with api

---

config/pipeline.yaml

The YAML pipeline configuration is getting finalised and storage_configs is being renamed to storage.  Update pipeline.yaml accordingly.

config/pipeline.yaml: rename storage_configs to storage

---

config/pipeline.yaml

Issue mentioned below will be reopened after merging this patch (this patch only partially covers use cases required to close the issue).
Fixes: kernelci/kernelci-api#295

config/pipeline.yaml: Add minnowboard-turbot-E3826 to baseline tests

---

config/pipeline.yaml
config/runtime/kbuild.jinja2

This patch add minimal support for firmware fetching and config fragments handling.
This is intermediate step, to unblock other teams implementing more features(event filtering, lava template, etc.), and will allow testing on much more devices.
Also builds config fragments merging is not correct right now, so this going to be improved in next PR.

config: Improve kbuild configurability (fragments + firmware)

---

config/pipeline.yaml

Minnowboard Turbot E3826 is currently in use as a generic x86 board. It might be decomissioned soon. This patch introduces a new generic x86 board with planned long-term support in the Collabora LAVA labs.

config/pipeline.yaml: add aaeon-UPN-EHLX4RE-A10-0864 to baseline tests

---

config/pipeline.yaml

This patch adds required configuration for LAVA TestJob definition for qemu device_type. Context section was converted to a conditional one in the base template as a part of kernelci/kernelci-core#2153
This patch allows generating equivalent LAVA TestJob definitions.

config/pipeline.yaml: add context to qemu platform/device_type definition

---

config/pipeline.yaml

Add first Chromebook in pipeline testing
Depends-on: https://github.com/kernelci/kernelci-core/pull/2176

pipeline.yaml: Add Chromebook for testing on x86-board kernels

---

config/runtime/kbuild.jinja2

modules.tar.xz complicates jinja templates and probably add some inflexibility in future, if we decide to change compression format. It is better to avoid also dots in artifact name.

kbuild.jinja2: Keep modules name simpler and neutral

---

src/timeout.py

Since the user schema has been changed in the API, update the logic to get `username` in `timeout` service.

src/timeout: update logic to get username of current user

---

config/pipeline.yaml
docker-compose.yaml

As good example for future improvements and to detect bugs in corner case we can add also one more lab and device. This is also unfortunately required to add one more real hardware device, as production lab doesn't support properly Azure files (yet), and it might be also good case to improve (detect infrastructure failure).

pipeline.yaml: Add one more lab and board

---

config/pipeline.yaml

This enables testing on an additional device type. `octopus` is a good candidate as it's known to work fine with the legacy pipeline and also uses a pineview chip.

pipeline: add "octopus" Chromebook

---

src/scheduler.py

We are having quite often errors on LAVA submit, and this will cause scheduler to crash.
This is generic attempt to keep running on such failures, which might be handled better in future.

scheduler.py: Try to not fail if submit have exception

---

src/trigger.py

We might have several different instances, and owners should not interfere with each other.

trigger.py: Check latest commit nodes owned by token owner

---

config/pipeline.yaml

This enables baseline testing on more x86 devices, allowing some early stress testing of the pipeline and infrastructure.

pipeline: add more Chromebooks

---

src/scheduler.py

It will be useful to add runtime and platform name in node, as it will help to troubleshoot tests failures, build failures and etc.

scheduler: Add additional parameters for create_job_node

---

config/runtime/kunit.jinja2

Normalize field names, replace '.' characters with '_', as dots in fields are problematic with mongodb

config/runtime/kunit: fix artifact field names

---

README.md
config/kernelci.toml
src/lava_callback.py

This is follow up on discussion of PR:
https://github.com/kernelci/kernelci-pipeline/pull/377 https://github.com/kernelci/kernelci-core/pull/2258
Now workflow of enabling LAVA lab is simplified:
LAVA lab need to enable one or two tokens (two a bit more secure, as one will be used to submit job, another for callback), and provide name(description) of one of tokens to specify in pipeline.yaml.
Also in toml file we need to specify callback token value.

lava_callback.py: Rework lava callback authentication

---

config/pipeline.yaml

This patch generates the equivalent config from provided `pipeline.yaml`.
Verification:
```sh
python3 -c 'import yaml, pprint; f=open("config/pipeline.yaml", encoding="utf-8"); pprint.pprint(yaml.safe_load(f))'
```
The only difference in generated config between current HEAD and this patch should be two new anchors for frequently used device types, i.e.
```
'x86_64-device': {'arch': 'x86_64',
'boot_method': 'depthcharge',
'mach': 'x86'},
'x86_64-grub-device': {'arch': 'x86_64',
'boot_method': 'grub',
'mach': 'x86'}
```
Edit (difference after adjustments):
```
'x86_64-chromebook-device': {'arch': 'x86_64',
'boot_method': 'depthcharge',
'mach': 'x86'},
'x86_64-device': {'arch': 'x86_64',
'boot_method': 'grub',
'mach': 'x86'}
```

config/pipeline.yaml: fold frequently used device types

---

config/runtime/kbuild.jinja2

Without flag -e script will never fail and trigger build fail, which means we will have broken kernel builds submitted to LAVA lab.

kbuild.jinja2: bugfix, invoke script correctly

---

src/test_report.py

Job stats and details are missing in test reports. e.g. staging logs shows 0 runs and no details even if jobs data exists for particular `checkout` node:
```
today at 16:59:02[STAGING] kernelci/staging-stable staging-stable-20240119.0: 0 runs 0 failures
today at 16:59:02
today at 16:59:02Summary
today at 16:59:02=======
today at 16:59:02
today at 16:59:02Tree:     kernelci
today at 16:59:02Branch:   staging-stable
today at 16:59:02Describe: staging-stable-20240119.0
today at 16:59:02URL:      https://github.com/kernelci/linux.git
today at 16:59:02SHA1:     38272e396092098ffb59c8dd43fadf3e5a8cfcfb
```
Fix the issue by updating functions for getting job information from root node as per `Node` schema changes.

src/test_report: fix missing job stats and details

---

src/trigger.py

Fix multiple checkout node creation with the same revision commit. Update logic to check existing `checkout` node for specific commit as per `Node` schema changes.

src/trigger: fix duplicate `checkout` node creations

---

docker-compose-production.yaml
src/lava_callback.py

LAVA have very short timeouts for callbacks, so better to do job submission process asynchronously.

lava_callback: Job processing can be done asynchronously

---

config/kernelci.toml
docker-compose.yaml

Set the same output path for all scheduler instances, use the same consistent path as the rest of the pipeline stages.

pipeline.yaml: unify scheduler output path

---

config/pipeline.yaml

This PR based on #395 which provides the necessary `kbuild` job. It adds baseline tests for 2 different arm64 chromebooks on top of it so we can assess how this use-case is handled and add more devices in the future.

pipeline: add baseline tests for arm64 chromebooks

---

config/pipeline.yaml

Requirements:
* https://github.com/kernelci/kernelci-core/pull/2334
This PR adds support for "regular" ARM64 devices, booting using `u-boot`, including baseline tests for both the RPi 4 and Khadas VIM3 present in Collabora's LAVA lab.
It also includes some refactoring of the pipeline (mostly for avoiding redundant information and sorting definitions alphabetically) as a separate commit.
Manually crafted LAVA jobs based on this configuration (and the corresponding -core PR):
* [Pi4](https://lava.collabora.dev/scheduler/job/12662145)
* [VIM3](https://lava.collabora.dev/scheduler/job/12662147)

Add non-chromebook ARM64 devices

---

config/pipeline.yaml

We want to monitor this tree so we can test -rc releases targetting the stable branch before they're released. Add a build config for the 6.6 branch in the `stable-rc` tree.

pipeline: add stable-rc tree and build config for 6.6

---

src/scheduler.py

The `get_params()` function might return `None`, in which case we should abort job generation as it will fail anyway.

scheduler: abort job generation if params are invalid

---

src/scheduler.py

Depends on https://github.com/kernelci/kernelci-core/pull/2341
For the job running in k8s runtime, get k8s cluster name that ran the job and store it in the node data field i.e. `data.k8s_context`.

src/scheduler: store k8s context in the job node

---

src/scheduler.py

Remove debug log for printing job node.
Fixes: d916ba8 ("src/scheduler: store k8s context in the job node")

src/scheduler: remove debug log

---

src/scheduler.py

In some cases when some of job parameters doesn't match, for example dtb, we need to issue error and fail node early.
This should be registered, as in some cases this might be regression, for example if dtb got renamed.
Depends-on: https://github.com/kernelci/kernelci-core/pull/2348

scheduler.py: Add failcode and fail node when some job parameters missing

---

src/scheduler.py

Correct field name for storing k8s cluster name to `Node.data`. Set `data.job_context` field to align with model definition.
Fixes: d916ba8 ("src/scheduler: store k8s context in the job node")

src/scheduler: fix field name for storing k8s context name

---

config/runtime/kver.jinja2

This is a temporary fix until the actual fixes are in place in the API.

config/runtime/kver: workaround for kver job failure

---

config/pipeline.yaml

Now that it seems ARM64 devices work as expected with the pipeline, let's add more of those available in Collabora's LAVA lab.
This PR also includes one commit fixing the name of the default defconfig for armv7 devices.

Add more arm64 devices

---

config/pipeline.yaml
src/fstests/runner.py

Switch to using the new `platforms` config instead of the legacy `device_types`.
Also remove `base_name` attributes where unnecessary (it is now inferred from the node name if left unspecified) and drop now-unneeded `class` attributes.

pipeline: use the new platform config for the new system

---

config/pipeline.yaml
docker-compose.yaml

Add new lab to config file and one board as example.

pipeline.yaml: Add LAVA lab "broonie" to the labs list

---

src/lava_callback.py

As mentioned in https://github.com/kernelci/kernelci-api/issues/474, even if job failed, node still registered as pass, and trying to upload non-existing log file. Fix that, if job is not completed, set proper node status, and dont upload non-existing log file, if it is not present.
Fixes: https://github.com/kernelci/kernelci-api/issues/474
Depends on: https://github.com/kernelci/kernelci-core/pull/2363

lava_callback.py: Handle failed jobs properly

---

config/runtime/kver.jinja2

The hack was added as a temporary fix for `kver` job. As now the actual fix has been sent to the API, drop the hack from the job template.

kver.jinja2: delete hack for `kver` failure

---

config/pipeline.yaml

Monitor linux `next` tree. Add build configs for `master` and `stable` branches.

config/pipeline: enable `next` tree and build configs

---

config/pipeline.yaml

Created on top of https://github.com/kernelci/kernelci-pipeline/pull/441 to avoid rebase conflicts.
config/pipeline: enable `mediatek` tree and build configs
Monitor linux `mediatek` tree. Add build configs for `for-next` branch.

Enable mediatek tree

---

docker-compose.yaml

Using 172.17.0.1 assuming default docker subnet and single instance, that might not work in some cases.
Proper scenario is to use mapping in docker-compose file to hostname host.docker.internal.
This is part of the efforts to make local development setup easier.

docker-compose.yaml: Add proper mapping of gateway hostname

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/platforms-chromeos.yaml
config/runtime/tast.jinja2
config/scheduler-chromeos.yaml
kube/aks/lava-callback.yaml
kube/aks/monitor.yaml
kube/aks/nodehandlers.yaml
kube/aks/scheduler-k8s.yaml
kube/aks/scheduler-lava.yaml
kube/aks/tarball.yaml
kube/aks/trigger.yaml
src/fstests/runner.py
src/lava_callback.py
src/monitor.py
src/regression_tracker.py
src/scheduler.py
src/send_kcidb.py
src/tarball.py
src/test_report.py
src/timeout.py
src/trigger.py

This change adds a `tast-quickcheck-x86` job, running on 2 Intel-based devices in order to help debug the new Tast implementation.

config: pipeline: add initial Tast tests

---

src/timeout.py

In case of LAVA, for example, if task was not submitted properly, or callback didn't reached, timeout service will close such node after while, but in obscure state: job_id exist, state is done, and result is nul. Let's set result as 'incomplete', fill error_code for better clarity.
Probably fixes: https://github.com/kernelci/kernelci-api/issues/470

timeout.py: Fix result, error_code for nodes that timed out

---

src/regression_tracker.py

Alternative version of https://github.com/kernelci/kernelci-pipeline/pull/444 that doesn't depend on https://github.com/kernelci/kernelci-core/pull/2378

Refine node search and regression generation (alternative)

---

src/scheduler.py

Due to platform filters, `create_job_node()` could skip a node creation and return `None`. In such cases, we should stop processing immediately and quietly return.

scheduler: return early if node creation skipped

---

restart_services.sh

Environment variable `KCI_API_TOKEN` is required to run pipeline services. The variable is defined in `.env` file. Add a script to monitor `.env` file using `inotifywait` tool. If the file changes are detected, that is if the token is modified, restart all the services.

restart_services.sh: restart pipeline service when `.env` file changes

---

config/pipeline.yaml

As discussed on weekly, we are able to run inexpensive cluster, separate for staging at least. Let's try to use it.

pipeline.yaml: Use new kubernetes cluster

---

src/lava_callback.py

In some cases LAVA callback might return invalid node id, we need to handle that properly, without crashing.

lava_callback.py: Handle case when invalid node id submitted

---

config/runtime/kbuild.jinja2
config/runtime/kunit.jinja2

The `base/python.jinja2` template has evolved with changes to the `Job` class API. Reflect and leverage those changes in both the `kunit` and `kbuild` templates.
Depends on https://github.com/kernelci/kernelci-core/pull/2428

config: runtime: adapt to python template changes

---

setup.cfg
src/scheduler.py

Scheduler config entries can now contain rules to ensure jobs are only executed when certain conditions are met. This change ensures this check is properly conducted before actually attempting to run a job.
Depends on https://github.com/kernelci/kernelci-core/pull/2439

scheduler: apply rules before running job

---

config/pipeline.yaml
config/platforms-chromeos.yaml

This PR adds a few rules matching those currently present in the legacy configs. Most of those will have no effect for now, as we're either not monitoring the corresponding tree (e.g. `android`) or already ensure the proper defconfig/fragments are used through job definitions and platforms allocation.
The lab rules make sense nonetheless as we'll likely start monitoring the Android tree at some point.
I also think the rules for Mediatek Chromebooks make sense due to fairly recent upstream support of some of those.
I'd happily get rid of per-platform rules on "generic" devices (those found in `pipeline.yaml`) though and defconfig/fragments rules for Chromebooks (see `platforms-chromeos.yaml`).

Add rules based on legacy config

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Those were left aside for the initial implementation, we can bring them back now we're confident Tast tests generally run as expected on the new system.
Based on https://github.com/kernelci/kernelci-core/pull/2302

config: chromeos: add codec-related Tast tests

---

config/result-summary.yaml
config/result_summary_templates/generic-regression.jinja2
config/result_summary_templates/tast-regressions-x86_64__runtime_errors.jinja2
src/result_summary.py

Allow to use `null` search parameters in yaml presets.
Make the existing example preset `tast-regressions-x86_64` get only the regressions not linked to a runtime error and create a new example preset `tast-regressions-x86_64__runtime_errors` to show only the regressions linked to runtime errors.

result_summary: allow to define `null` search parameters in the yaml presets

---

src/scheduler.py

We need to mark jobs that failed to run due infrastructure or configuration issues as incomplete and such issues usually need admins attentions and more permanent fixes.

scheduler: mark jobs that we failed to submit as incomplete

---

config/jobs-chromeos.yaml
config/platforms-chromeos.yaml

Lots of parameters for chromebooks are mostly identical, only differing by a few characters which are device/family-specific.
For jobs, this mostly affects the kbuild defconfigs. Regarding platforms, each entry must specify the full URL to the Tast tarball, even though the format is identical.
Taking advantage of the recent ability to format string params using the object's own attributes (or other params), this change aims at simplifying the current Chromebook configs.
Depends on #459 https://github.com/kernelci/kernelci-core/pull/2438

config: chromeos: take advantage of params formatting

---

src/regression_tracker.py

When searching for previous test runs, don't assume all search parameters will be present, as some of them might be null.
~~**NOTE**: Pending to test in staging~~ Tested OK

src/regression_tracker: fix regression detection

---

config/platforms-chromeos.yaml
config/runtime/tast.jinja2

This PR reworks the `tast` template so it uses the new `device_dtb` parameter instead of the old `platform_config.dtb`. It also honors `platform_config.params.flash_kernel.dtb` if present, falling back to `device_dtb` otherwise.
The config for `trogdor-kingoftown` is updated so it can use either the old DTB file name (up until 6.3.x) or the new one (renamed starting with 6.4-rc1), while still using the correct file name for the "flash kernel" (which is based on 6.1).
Depends on https://github.com/kernelci/kernelci-core/pull/2471

Fix Tast tests on `trogdor-kingoftown` with kernels >= 6.4

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/scheduler-chromeos.yaml

Enable the DT kselftest for MediaTek Chromebooks.

Enable DT kselftest for MediaTek Chromebooks

---

.gitignore
config/kernelci.toml
docker-compose.yaml
src/monitor.py
src/patchset.py
src/tarball.py

Patchset service process patchset nodes:
- Wait for parent checkout node to be available
- Download checkout node tarball
- Apply patches and calculate patchset hash
- Upload new tarball

src/patchset.py: Implement Patchset service

---

src/scheduler.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/508
It is helpful for debugging to catch error message when scheduler fails to submit job to runtime.
Store the error message in `data.error_msg` field.

T40464 src/scheduler: store error message when job fails with "submit_error"

---

config/pipeline.yaml

The test was introduced upstream in version 6.7, so no point in trying to run it on earlier versions.

config: pipeline: Set minimum kernel version for DT kselftest to 6.7

---

config/result-summary.yaml

stable-rc-build-failures and stable-rc-boot-failures weren't querying specifically for test failures.

result_summary: fix result presets

---

src/regression_tracker.py

**DEPENDS ON**: https://github.com/kernelci/kernelci-core/pull/2476
Take into account "active" and "inactive" regressions when creating them and when processing new passed or failed nodes.
When a node passes, it checks if it "inactivates" an existing "active" regression. When a node fails, it checks if it needs to create a new regression or update an existing "active" one.

src/regression_tracker: rework regression detection

---

src/regression_tracker.py

Fixup for commit fcb29501663d78920bcd129bd57c36b9af624bc4 If the "result" field is ever made non-optional in the models we can probably remove this.

regression_tracker: [trivial] make regression active by default

---

src/regression_tracker.py

Fixup for commit fcb29501663d78920bcd129bd57c36b9af624bc4 If the "node_sequence" field is ever made non-optional in the models we can probably remove this.

regression_tracker: [trivial] set default empty node sequence

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Several Tast tests can only fail in the context of KernelCI:
* `video.PlatformDecoding.v4l2_state*_vp9_0_svc` do not actually exist, causing the whole test job to fail
* `platform.DLCService*` and `platform.Memd` rely on features only present in the downstream Chrom{e,ium}OS kernel (see b/247467814 and b/244479619 for those having access to Google's issue tracker)
* `kernel.ConfigVerify.chromeos` relies on downstream-only config options such as `CONFIG_SECURITY_CHROMIUMOS` and other similar ones, and therefore can only fail when testing upstream kernels
HEVC tests are also expected to either fail or be skipped as ChromeOS [doesn't handle hardware decoding](https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/accf64c6d3df95945c42ab6740dedddea556f218) for this codec. This …

config: chromeos: remove/disable meaningless Tast tests

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

As a follow-up to #520 this PR ensures more always-failing tests are disabled. This is a separate PR as this part requires https://github.com/kernelci/kernelci-core/pull/2490 to actually give the expected results.
It contains 2 parts/commits:
* exclude tests failing on all platforms and all kernel versions
* exclude *some* tests when testing kernels < 6.7 on qcom/trogdor devices (those tests pass with 6.7+)
The 2nd part is a bit more involved as it required duplicating test jobs and setting the proper rules on each variant so only the appropriate one is executed depending on the version of the kernel being tested.
Depends on https://github.com/kernelci/kernelci-core/pull/2490 (without it `excluded_tests` will only be ignored, but otherwise that should be "mostly harmless").

config: chromeos: remove/disable more failing Tast tests

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Enable the baseline test on all the supported Chromebooks. Also, generalize the Chromebook platform anchors by dropping the "stoneyridge" and "pineview" naming.
This PR relies on https://github.com/kernelci/kernelci-core/pull/2459 to remove bootrr from the baseline template.

Enable baseline test on all the Chromebooks

---

src/result_summary/monitor.py
src/result_summary/summary.py
src/result_summary/utils.py

Split the post-processing of nodes to a common function that can be used for both summary and monitor modes. Currently, post-processing involves only the collection of logs.

result_summary: post-process results for summary and monitor modes

---

config/pipeline.yaml

Add definitions of android-mainline from legacy system to the new system.
Add android-mainline tree
~~Add lab-kontron and lab-pengutronix definitions~~
~~Add respective platforms~~
NOTE: please review this, I didn't test and I wrote based on what I saw from current code and legacy code, so I'm very unsure about this. Please let me know if there is any better way to check/test it.
Reference: https://github.com/kernelci/kernelci-pipeline/issues/483

pipeline: Add android-mainline

---

config/kernelci.toml

Fixes https://github.com/kernelci/kernelci-pipeline/issues/538
Currently set `60 min` timeout is not enough as some `kbuild` jobs and its sub-tests take around 2 hrs to complete after getting submitted to runtime.
Here is an example from staging. See the information for a `checkout` and its child nodes:
| id                       | name                | created                    | updated                    | timeout                    |
|--------------------------|---------------------|----------------------------|----------------------------|----------------------------|
| 661c9d59b60b785eb9fc42b0 | checkout            | 2024-04-15T03:22:01.317000 | 2024-04-15T03:51:03.870000 | 2024-04-15T04:22:01.284000 |
| 661c9d97b60b785eb9fc42b4 | kbuild-gcc-10-arm64 | 2024-04-15T03:23:03.399000 | …

kernelci.toml: set `checkout` node timeout to `180 min`

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Enable the baseline-nfs test on all the supported Chromebooks, with both the default and the chromeos kernel configurations.

 Enable baseline-nfs test on all the Chromebooks

---

src/timeout.py

For `TIMEOUT` mode, set `checkout` node result to `fail` if its state is `running` as it means code checkout is still going on and node timed-out. Set it to `pass` if its state is any other than `running`.
Set `checkout` node result to `pass` if mode is `DONE` as it means once `checkout` has been in `available` or `closing` state and it could successfully complete source code checkout.

src/timeout: set `checkout` result

---

src/regression_tracker.py

Handle the case of a failed test run when it's the first occurence of that test case. Consider it "not a regression" for now, since we're defining a regression as a "breaking point" between a success and a failure.
I suggest we leave this running on staging for a while to see if the issue happens again, although it may be hard to catch. ~I'll try to test it locally next Monday.~ -> Tested locally already: OK

regression_tracker: bugfix, failed test with no prior runs

---

config/platforms-chromeos.yaml
config/scheduler-chromeos.yaml

Due due to a copy/paste mishap, the device type for `asus-CM1400CXA-dalboz` had a trailing `_chromeos`, leading LAVA to fail finding the correct device type, and no job from the new system running on this platform.

config: platforms-chromeos: fix dalboz device type

---

config/jobs-chromeos.yaml
config/platforms-chromeos.yaml
config/scheduler-chromeos.yaml

Drop non-existent platform and limit Tast tests to 5.4+: those can't run on earlier kernels due to missing filesystem features, and that causes false positives when trying to identify corrupt devices.

Small improvements to ChromeOS configs

---

src/timeout.py

Fix a glitch in the code related to setting `checkout` node result.
Fixes: 361fc0d ("src/timeout: set `checkout` result")

src/timeout: a bug fix in `_submit_lapsed_nodes`

---

config/pipeline.yaml

We are moving k8s from eastus to westus3 as it is cheaper

pipeline.yaml: Update early access FQDN

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/platforms-chromeos.yaml

This PR addresses 2 issues:
* the naming of 32-bits ARM architecture (`armel`) can be confusing to some and has different meanings for different systems; rename to `arm` so it makes more sense
* replace hardcoded system-dependent architecture strings with the corresponding properties (`crosarch`, `debarch`, `karch`)
Depends on https://github.com/kernelci/kernelci-core/pull/2504

Improve architecture naming and format strings

---

src/tarball.py
src/timeout.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/554
Depends on https://github.com/kernelci/kernelci-core/pull/2507
- Tarball updates source code repo and creates tarball. If update repo operation fails even with the second attempt, it means it failed to checkout souce code. Hence, update `checkout` node with state `done` state and result `fail`.
- Set timed-out `checkout` node result to `incomplete` while in `running` state. As it denotes that the node timed-out while checkout was still going on.

Handle incomplete/failed checkout

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/scheduler-chromeos.yaml

Start tracking the [collabora-next](https://gitlab.collabora.com/kernel/collabora-next) tree, a linux-next based tree maintained by Collabora and used to track patches on the way to upstream.
Enable the [ACPI kselftest](https://github.com/kernelci/kernelci-pipeline/commit/050ccd051d38c5b1d05750cdc6c8f1686fc66ab1) on the collabora-next tree for the Intel Chromebooks in the Collabora LAVA lab, to perform some preliminary testing and verify the test is working as expected.

Track collabora-next tree and enable ACPI kselftest

---

src/result_summary.py
src/result_summary/utils.py

Restore this function that was accidentally removed during the last refactoring.

result_summary: restore missing split_query_params function

---

src/lava_callback.py

There is no use for lot of empty files on Azure,
that only complicate cleanup.

lava_callback: Don't upload empty files to Azure

---

src/lava_callback.py

It can be useful to know the exact device on which a job ran, without having to open the LAVA job page. This is done by querying the device ID from the callback data and appending it to the node data.
Depends on https://github.com/kernelci/kernelci-core/pull/2519
Fixes https://github.com/kernelci/kernelci-core/issues/2502

src: lava_callback: add device ID to node data

---

config/result_summary_templates/generic-test-failures.html.jinja2

The object is named test and not node, so s/node/test

result_summary_templates: fix error 'node' is undefined

---

config/runtime/kunit.jinja2

Depends on https://github.com/kernelci/kernelci-core/pull/2517
Fixes https://github.com/kernelci/kernelci-pipeline/issues/567
Set `node.data.arch` field for `kunit` test nodes.

Set architecture info for `kunit` test nodes

---

config/result-summary.yaml
config/result_summary_templates/generic-test-results.html.jinja2
config/result_summary_templates/generic-test-results.jinja2

result-summary.yaml: add preset to list android build tests
Since we now build android, add a preset to allow result-summary.yaml to
list all build results from Android tree.
also:
result_summary_templates: make generic-test-failures generic to all
results
The generic-test-failures templates can be used to show general results
just replacing the name "failures" by "results". Makeing it easier to be
re-used by communities that want to have pre-sets to list all results of
the tests, so:
s/generic-test-failures/generic-test-results
To properly work, this change requires https://github.com/kernelci/kernelci-pipeline/pull/580

Add Android build preset

---

config/jobs-chromeos.yaml

Commit d4bbe942098b ("kbuild: remove CONFIG_MODULE_COMPRESS"), introduced in kernel v5.13, substituted CONFIG_MODULE_COMPRESS=n for CONFIG_MODULE_COMPRESS_NONE=y as the way to disable module compression. Since module compression causes "Invalid ELF header magic: != ELF" errors during boot on the ChromeOS base config, add the missing config to disable module compression on kernels > v5.13 as well.

jobs-chromeos.yaml: Disable module compression for every kernel version

---

config/platforms-chromeos.yaml

This ensures we use the new version of the `install-modules` script.

config: platforms-chromeos: use new cros-flash image

---

config/result_summary_templates/generic-regression-report.html.jinja2
config/result_summary_templates/generic-regression-report.jinja2
config/result_summary_templates/generic-regressions.html.jinja2
config/result_summary_templates/generic-test-failure-report.html.jinja2
config/result_summary_templates/generic-test-failure-report.jinja2
config/result_summary_templates/generic-test-results.html.jinja2
src/regression_tracker.py

With the `device` field now being available, it can be interesting to add this information to both regression nodes and results summary reports.
Depends on https://github.com/kernelci/kernelci-core/pull/2519

Use "device" field in regression tracker/results summary

---

config/jobs-chromeos.yaml
config/runtime/v4l2-decoder-conformance.jinja2
config/scheduler-chromeos.yaml

Enable first fluster test, AV1-TEST-VECTORS for mt8195-cherry-tomato-r2. Run the test on mainline and next until more trees are added.
Note: This is my first PR. Please review it and I'll improve it. https://github.com/kernelci/kernelci-core/pull/2535 is a pre-requisite for this.

config: enable first fluster test for mt8195-cherry-tomato-r2

---

config/pipeline.yaml
config/scheduler-chromeos.yaml

Enable cpufreq kselftest on all the trees and branches.

config: chromeos: Enable cpufreq kselftest

---

config/jobs-chromeos.yaml
config/platforms-chromeos.yaml

ChromeBooks were upgraded with a new image based on ChromiumOS R124, so we must use those files now.

config: platforms-chromeos: use CrOS R124 files

---

config/result-summary.yaml

We're interested in catching regressions and failures in the both the kselftest-acpi test suites and its test cases. Match the nodes by group in the presets accordingly.

result_summary presets: fix acpi kselftest presets

---

src/regression_tracker.py
src/result_summary/monitor.py
src/tarball.py
src/test_report.py

Depends on https://github.com/kernelci/kernelci-core/pull/2550
`APIHelper.receive_event_node` method is used to receive node data from PubSub event. The method has been updated to return `is_hierarchy` flag as well which represents events related to node hierarchy.
Update pipeline services using the method accordingly.

src: update return values of `APIHelper.receive_event_node`

---

src/lava_callback.py

Sometimes due congestion node might be set to timeout, but then result might arrive late and we need to use it properly.

lava_callback.py: Remove error_code/error_msg on lava-callback

---

config/result-summary.yaml

Fix the dt kselftest preset, just like was done for the acpi one, as the current preset doesn't match the actual results we're interested in.

result_summary presets: fix dt kselftest presets

---

doc/connecting-lab.md

Fixes: https://github.com/kernelci/kernelci-pipeline/issues/473
Refine documentation for connecting LAVA labs and submitting jobs to the lab.

doc/connecting-lab: refine documentation

---

config/pipeline.yaml
docker-compose.yaml

Closes: https://github.com/kernelci/kernelci-project/issues/358
- config/pipeline.yaml: add lab config for Qualcomm
- config/pipeline.yaml: add `baseline-x86` job for qualcomm
- docker-compose.yaml: add lab-qualcomm runtime
- config/pipeline.yaml: add `baseline-arm64` job for qualcomm

Enable qualcomm LAVA lab

---

src/lava_callback.py

As we use this data in reports, lets remove all
non-printable characters as they confuse grafana, browsers and others.

lava_callback.py: Sanitize lava log data

---

config/runtime/kunit.jinja2

Addresses one of the issues from https://github.com/kernelci/kernelci-api/issues/536
Fix result map for skipped tests. Initially, API didn't have `skip` available node result in the schema. That's why it was 
mapped to `None` result. But now API has `skip` result to denote skipped tests.
Fix the result mapping accordingly.

config/runtime/kunit.jinja2: fix result map

---

config/jobs-chromeos.yaml
config/pipeline.yaml

Add the lab-setup fragment to the chromebook builds, which contains the architecture independent kernel configs needed to run tests on the platform. Notably this disables IP autoconfig by the kernel.
The result of this change is that the 12 seconds boot delay and the consequent deferred probe pending warnings will no longer happen on any platform. Particularly on mt8186-corsola-steelix-sku131072 (due to a different network adapter being used) on which it was still happening.

config: jobs-chromeos: Add lab-setup fragment

---

config/jobs-chromeos.yaml
config/runtime/watchdog-reset.jinja2
config/scheduler-chromeos.yaml

Add a basic test to verify watchdog reset functionality. Enable the test on all ARM64 and AMD x86_64 Chromebooks. For Intel Chromebooks, enable the test only on octopus, as ACPI PM Timer on the other devices has been disabled in coreboot.
Requires: https://github.com/kernelci/kernelci-core/pull/2562

config: chromeos: enable watchdog reset test on Chromebooks

---

config/jobs-chromeos.yaml

Related PR: https://github.com/kernelci/kcidb/pull/530
Add KCIDB test suite mapping for `watchdog_reset` test.

config/jobs-chromes: add kcidb test suite property for watchdog test

---

src/send_kcidb.py

Add error metadata fields such as `error_code` and `error_msg` to `misc` field for build nodes.

src/send_kcidb: add error info to build nodes

---

src/send_kcidb.py

Tweak condition to get error metadata for test nodes. It should get error info for incomplete nodes as well and not just failed nodes.

src/send_kcidb: get error metadata for failed/incomplete tests

---

src/send_kcidb.py

All test suite definitions must have `kcidb_test_suite` property i.e. KCIDB test suite mapping.
Only send tests for those the mapping is found.

src/send_kcidb: send tests only if KCIDB test mapping exists

---

tests/validate_yaml.py

To submit KernelCI generated data to KCIDB, it is required to have a mapping for all the job definitions with
`kcidb_test_suite` property.
Add validation to ensure all the jobs have a mapping present to avoid missing data submission. This check is to notify test authors trying to enable tests in maestro to include the required property for the mapping in their definition.

tests/validate_yaml: add validation for KCIDB mapping

---

config/platforms-chromeos.yaml

Add test_character_delay to the Spherion and Tomato platforms to workaround the fact that they're sometimes unable to process serial input fast enough, resulting in mangled commands and consequently flaky test results, as described in
https://github.com/kernelci/kernelci-project/issues/366.
The right place to do this change would be in the device-type template as described in LAVA's documentation [1]. This overriding in KernelCI is meant only as a temporary workaround to verify whether this fixes the issue. If it does, then we'll do it in LAVA upstream instead.
[1] https://docs.lavasoftware.org/lava/debugging.html#differences-in-input-speeds
Signed-off-by: Nícolas F. R. A. Prado <nfraprado@collabora.com>

config: platforms-chromeos: Add serial delay for some MediaTek platforms

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Run the error-logs kselftest on MediaTek Chromebooks. This test is currently under review upstream [1] so, in the meantime, it has been added to the collabora-next tree so it can prove its value by helping to detect issues upstream.
[1] https://lore.kernel.org/all/20240423-dev-err-log-selftest-v1-0-690c1741d68b@collabora.com
Fixes #606.

config: chromeos: Enable error-logs kselftest for MediaTek Chromebooks

---

config/pipeline.yaml
docker-compose.yaml

Addresses https://github.com/kernelci/kernelci-project/issues/361

Enable CIP lab

---

src/send_kcidb.py

Depends on https://github.com/kernelci/kernelci-pipeline/pull/628
Parse newly added job node and its child tests for KCIDB submission.

KCIDB submission: parse job nodes

---

src/send_kcidb.py

Depends on https://github.com/kernelci/kernelci-pipeline/pull/639
`setup` test suite has been introduced to store test results for environment setup checks before running an actual test suite.
KCIDB doesn't require `setup` test suite result as long as the main test job result is submitted.

KCIDB submission: skip `setup` tests submission

---

src/send_kcidb.py

Do not retrieve artifacts or metadata from parent node for skipped tests as in pratice only kernel revision, test runtime and platform will be available for skipped tests.

KCIDB submission: handle skipped tests

---

src/result_summary/utils.py

Make the script continue running if there was an error fetching a test log.

result_summary/utils: ignore failures on log retrieval

---

doc/developer-documentation.md

Closes https://github.com/kernelci/kernelci-pipeline/issues/573
Add developer documentation for enabling new tests.

doc/developer-documentation: add docs for enabling new tests

---

README.md

Documentation has been migrated to the "docs.*" subdomain.
Thanks Minas Hambardzumyan for reporting the issue!

Fix links after docs page migration

---

config/pipeline.yaml

Add useful low-overhead debug option to kernel,
and test on most x86 boards we have available,
with minimal baseline tests.

pipeline.yaml: Add kcidebug fragment

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/scheduler-chromeos.yaml

As we upgrade compiler images, we need update gcc version

configs: update gcc-10 to gcc-12

---

src/regression_tracker.py

Don't use 'path' as an api search parameter. The use of lists as query parameters (path is a list) is undefined. Instead, do the filtering in code.
**NOT TESTED YET**, waiting to see it running on staging

regression_tracker: workaround: match node paths programmatically

---

config/pipeline.yaml

QEMU jobs use container pulled from hub.docker.com. After the lab move pulling from this registry is no longer possible at Qualcomm. This patch disables QEMU jobs from Qualcomm lab.

config: remove qemu jobs from lab-qualcomm

---

config/pipeline.yaml
tests/validate_yaml.py

Add validation that scheduler entries have matching job entry, this is critical validation, and job entries have at least one entry in the scheduler.
Fix one entry detected by this validation

validate_yaml.py: Improve pipeline validation

---

config/kernelci.toml

As we agreed to refer new KernelCI API & Pipeline as "maestro", use the new name while submitting data
to KCIDB.

config/kernelci.toml: update KCIDB origin name

---

config/pipeline.yaml
config/result-summary.yaml

See the description in individual commits.

Enable rt-stable builds in new KernelCI

---

config/jobs-chromeos.yaml

The baseline test is currently run with both ramdisk and nfs rootfs. To distinguish baseline-nfs tests in KCIDB, add an 'nfs' suffix to the KCIDB test suite name.

config: chromeos: Add 'nfs' suffix to KCIDB suite name for baseline-nfs

---

kube/aks/trigger.yaml

Ignore kernelci tree on production, as it is special "staging"-only tree, and read all /config directory, not just default pipeline.yaml.

kubernetes: Adjust trigger k8s options

---

src/regression_tracker.py

Fix _get_last_matching_node(), after the previous change there was an unhandled scenario where nodes may be empty but the function wouldn't return None immediately.

regression_tracker: bugfix: catch empty search condition

---

config/scheduler-chromeos.yaml

As per discussion, we disable temporary tast tests which unlikely will be reviewed.

scheduler-chromeos.yaml: Temporarily disable non-essential tast tests

---

config/pipeline.yaml

Android UM builds are already enabled. This PR enables android builds for arm, arm64, x86, i386, riscv with gcc-12 and clang-17.

Enable Android builds in different configurations with gcc-12 and clang-17 both

---

config/jobs-chromeos.yaml
config/pipeline.yaml
src/send_kcidb.py

Use `boot` as KCIDB test suite mapping for all baseline tests.

config: update KCIDB test suite mapping for baseline

---

README.md
config/pipeline.yaml

As we are moving callback URL to environment variable, updating config and README accordingly.

callback_url: Update config and README

---

src/scheduler.py

When someone generate artificial event with jobfilter, this is likely maintainer trying to repeat job. Treat this accordingly, and inject job filter to job node, so we will run only tests maintainer wants.

scheduler.py: If event have jobfilter, inject it to the node data

---

docker-compose-production.yaml
docker/lava-callback/requirements.txt
src/lava_callback.py

It will be easier to maintain API and Pipeline, as both will be powered by FastAPI framework.

lava_callback: migrate to fastapi

---

config/jobs-chromeos.yaml

Update fluster rootfs URL. 
**Note:** I manually built a rootfs on staging to test  the changes in https://github.com/kernelci/kernelci-core/pull/2599 . Once the PR is tested and merged, we'll need to update the URL to one in production.

config: chromeos: Update fluster rootfs URL

---

config/runtime/kbuild.jinja2

As required in https://github.com/kernelci/kernelci-core/pull/2608 defconfig might be two types. Support it in jinja2 accordingly.

kbuild.jinja2: support defconfig as list or str

---

config/pipeline.yaml

It has been confirmed with Todd that we should remove the deprecated branches. Hence remove those branches.

config: pipeline: Remove android's deprecated branches

---

config/pipeline.yaml

The allmodconfig generates very large kernel image. It cannot be booted on the arm64 and arm targets as tftp errors out that size is too large. Reduce the kernel image size. Use the default defconfig. The same defconfigs have been booting for other trees.

config: pipeline: run baseline on non-allmodconfig for android

---

doc/developer-documentation.md

- Fix a minor bug in YAML block formatting
- Rename a section from "Enabling a new Kernel tree" to "Enabling new KernelCI trees and tests" as it explains enabling tests as well
Fixes: f5f57de ("doc: developer-documentation: Update documentation by adding more details")

Fix "Enabling new tree" section

---

config/jobs-chromeos.yaml
config/pipeline.yaml

For cases where we want a single branch to be allowed for a given tree, we can now use the `tree:branch` format in rules. Convert existing rules accordingly.
Depends on https://github.com/kernelci/kernelci-core/pull/2613

config: use the new `tree:branch` format for rules

---

config/pipeline.yaml

The `filters` param was used in the legacy system but has been replaced by `rules`, with a different syntax.
For Android RISC-V builds, this was used to deny job execution on kernels < 4.19, so let's translate this condition with the rules format, and do a similar change for the `rt-tests`-based jobs.

config: pipeline: fix improper use of "filters" attribute

---

config/pipeline.yaml

The kcidebug jobs that run on MediaTek and Qualcomm platforms should have arm64 in the name rather than x86. Fix the typo.

config/pipeline.yaml: Fix x86 typo in kcidebug job names

---

config/pipeline.yaml

The parameters are only needed when they are changed or appeneded. Remvoe the parameters which aren't being modified.

config: pipeline: remove params

---

.github/workflows/main.yml

Automatically add label so broken PR wont go to staging

workflows: Add label on CI check failures

---

.github/workflows/main.yml

GH token by default dont have permission to change label if PR opened from other repo. Attempts to change permissions in settings didnt helped.
Rant:Worst part of workflows, it is very difficult to simulate various situations, as there is no proper debugger.

workflows: Add token permissions

---

.github/workflows/main.yml

Revert autolabeling.
If we run it in pull_request context - we cannot add labels, if someone create PR from their repo. (This is our normal workflow)
pull_request_target have too many security implications
Providing PAT token will need periodic maintenance due expiration and still gives a bit too wide permissions

Revert autolabeling

---

doc/developer-documentation.md

Add details about specifying scheduler job rule for a specific branch of a specific tree.

doc/developer-documentation: document `tree:branch` rule

---

config/pipeline.yaml

Docker type can't really run on production (because pipeline runs in k8s itself), and even in staging it is DinD and makes unnecessary high load on each run. Disable, but dont remove, as later we might use such type for some lightweight staging jobs.

pipeline.yaml: Disable docker kunit

---

config/platforms-chromeos.yaml

Add `test_character_delay` to Jacuzzi Chromebooks, similar to other Mediatek Chromebooks. This workaround addresses the issue of not processing serial input quickly enough, which may cause output mangling and inconsistent test results.
This is a temporary workaround to identify the correct delay value. The proper place to define the delay is the LAVA device dictionaries.
Similar to: https://github.com/kernelci/kernelci-pipeline/pull/626
Instance of test failure caused by corrupt serial output, causing a false regression on this platform (`ttyS ttyS0: 1 input overrun(s)` is also reported in the log): https://lava.collabora.dev/scheduler/job/14838004#L6255

config: platforms-chromeos: Add serial delay for Jacuzzi

---

config/logger.conf
docker-compose-kcidb.yaml
docker-compose.yaml
src/logger.py
src/patchset.py
src/scheduler.py
src/tarball.py

Closes https://github.com/kernelci/kernelci-project/issues/334
Enable multiple log streams for `Logger`.
Create a file handler to dump logs to files. Use stream and file handlers for all the pipeline services to redirect logs to both the streams including `stdout` and log file.
Update the logger config file.

Enable log file support

---

src/send_kcidb.py

For the convenience of data analysis on KCIDB dashboard, submit all the job nodes irrespective of node results.

src/send_kcidb: submit all job nodes

---

config/scheduler-chromeos.yaml

This device's hardware decoder is able to process H.264, VP8 and VP9.

config: scheduler-chromeos: enable codec Tast tests on corsola

---

config/pipeline.yaml

Enable chrome-platform tree and its 2 branches. Only builds are run over
it over default configs on arm, arm64 and x86.
The job for arm64 is being created as there is no other suitable job
with only arm64-chromebook. (There is kbuild-gcc-12-arm64-chromebook-kcidebug
which has kcidebug fragment.) No need to create job for x86 as
kbuild-gcc-12-x86 covers it. Specify chrome-platform tree in
kbuild-gcc-12-arm-multi_v7_defconfig.
Closes https://github.com/kernelci/kernelci-project/issues/422

config: pipeline: Port chrome-platform to new KernelCI

---

config/jobs-chromeos.yaml

With recent CrOS versions, those jobs can run for a veeery long time (> 2hrs). Increase the job timeout to 3 hrs so we can finally get meaningful results.
Depends on https://github.com/kernelci/kernelci-core/pull/2621

config: jobs-chromeos: set large timeout for `tast-decoder-chromestack`

---

config/logger.conf
src/logger.py

Fixes https://github.com/kernelci/kernelci-pipeline/issues/682
Use timed rotating file handler to optimize storage space for log files instead of using a regular file handler.
It will create a new log file with `<service-name>.log` convention and keep one backup file for older logs than
7 days. It will delete older backup log files on rollover if exists.
In case of `logs` directory is not mounted due to a different environment such as `k8s`, the service would crash with
`FileNotFoundError`. Enable only console logging when file logging fails to fix the issue.

Use timed rotation logging

---

src/lava_callback.py
tools/kci-maintainer

Before user can use reference nodeid and custom commitid to submit custom checkout node.
Now we allow also user to submit tree information and jobfilter, but all this data will be validated in config, e.g. user can submit tree that only exist in pipeline configs, job names that exist in jobs: and etc.

lava_callback.py: Extend /checkout endpoint functionality

---

config/pipeline.yaml

Enable arm64 tree and its branch for-kernelci. The builds are run over
arm64 only in defconfig and allnoconfig. The defconfig case is already
covered by kbuild-gcc-12-arm64. There is no allnoconfig job available
already. Hence create a new job and schedule it.
closes https://github.com/kernelci/kernelci-project/issues/423
Signed-off-by: Muhammad Usama Anjum <usama.anjum@collabora.com>

config: pipeline: Enable arm64 tree

---

config/pipeline.yaml
config/scheduler-chromeos.yaml

The rt-tests were wrongly set to trigger based on chromebook jobs which didn't had preempt-rt fragment. Fix it by specifying the correct event which is the name of preempt-rt kbuild job names. Run each of 4 enabled rt-test on each variant of kernel. The kbuild variant are 2 arm64, 2 x86 and 1 arm.
Schedule the tests on a few devices instead of scheduling on all of the devices. Select devices from different vendors for each architecture.

config: pipeline: fix rt-tests scheduling

---

config/pipeline.yaml

Note: this PR is mostly there to indulge my OCD, although I believe it can be useful for long-term maintainability.
This makes it easier to find a specific entry location within the file if one knows the entry's name. It also prevents chaos within this file which, as everyone knows, is likely a good thing.
Some future CI check to ensure things stay ordered that way would likely be good as well, but is not included in this change.
Includes #728, draft and `staging-skip` for the same reasons.

config: pipeline: sort top-level entries alphabetically

---

config/jobs-chromeos.yaml
config/pipeline.yaml

A few entries were still left improperly ordered, both in the main pipeline config and in ChromeOS jobs definitions, as reported by `kci config validate`. Let's fix those.

config: fix remanining sorting issues

---

config/pipeline.yaml

Enable tip and its master branch. Only builds are run on this branch on all architecture. So add tip to the list of build-only trees.

config: pipeline: Enable tip tree

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/runtime/generic.jinja2
config/runtime/kselftest.jinja2
config/runtime/sleep.jinja2
config/runtime/v4l2-decoder-conformance.jinja2
config/runtime/watchdog-reset.jinja2
config/scheduler-chromeos.yaml
doc/developer-documentation.md

Add basic test to verify basic WiFi functionality. Enable the test on ARM64 and x86_64 Chromebooks.
Requires: https://github.com/kernelci/kernelci-core/pull/2581

config: chromeos: enable wifi basic test on Chromebooks

---

kube/aks/regression.yaml

By some reason regression tracker was not added in kubernetes manifests, and recently discovered by Ricardo. Fixing that.

feat(k8s): Add regression tracker manifest

---

src/send_kcidb.py

As KCIDB only supports `pass` and `fail` status for builds and doesn't have a separate status for incomplete/missed build jobs, keep `valid` flag empty for incomplete builds.

src/send_kcidb: handle incomplete builds

---

config/pipeline.yaml

Enable all the trees which build minimal configurations
Following trees are being enabled:
- krzysztof
- lee-backlight
- linusw
- net-next
- omap
- pm
- renesas
- robh
- rppt
- soc
- tegra
- thermal
- ulfh
- vireshk

Enable 14 minimal build trees

---

config/pipeline.yaml

Several job definitions use `nfsroot` as part of the base attributes of the job, instead of setting it under `params`. This leads to `nfsroot` not being properly passed to the templating engine, which then uses the default value instead of the one present in the job definition.
Fix this in affected jobs, and set `boot_commands: nfs` for every job which defines `nfsroot`.

config: pipeline: fix `nfsroot` usage in job definitions

---

src/lava_callback.py

Previously when pipeline endpoints were called pointing to an existing Maestro Node the request had to specify a Job filter. This patch drops this requirement allowing executing "kci-maintainer --nojobfilter" commands.
Fixes: #763

lava_callback: Drop jobfilter requirement

---

docker-compose.yaml

Result-summary doesn't work properly on staging as it dont have proper config. Do not restart if it fails.

fix(docker-compose): Disable restart for result-summary

---

src/send_kcidb.py

Depends on https://github.com/kernelci/kernelci-core/pull/2644, https://github.com/kernelci/kernelci-pipeline/pull/760
Device tree compatible information has been added to platforms configuration in YAML files. 
Load the value if available and send it along with KCIDB test submission.

src/send_kcidb: load `compatible` field

---

config/pipeline.yaml

New package has been added to bookworm-rt rootfs. Hence update the URL to newly updated rootfs.
Related PR: https://github.com/kernelci/kernelci-core/pull/2614

config: pipeline: Update bookworm-rt rootfs

---

config/jobs-chromeos.yaml

To distinguish different fluster tests on KCIDB dashboard, use syntax `fluster.v4l2.<media_framework>_<codec>` for KCIDB test suite mapping property.
This would make stats analysis possible such as total number of passed and failed tests for summary reports.

config/jobs-chromeos.yaml: update `kcidb_test_suite` for fluster tests

---

config/pipeline.yaml

On request of rt-maintainer, enable the remaining tests. Keep the default timeout for now. As the test definitions are always present, only schedule these tests on all the different targets in the same manner as the previous rt-tests are being scheduled.

config: pipeline: Enable remaining tests from rt-test repo

---

src/lava_callback.py
src/send_kcidb.py
src/trigger.py

Closes https://github.com/kernelci/kernelci-core/issues/2654

Extend `node.submitter`

---

tools/kci-maintainer

- Fix getting token for `prepare_checkout` when token is not available in env variable
- Fix the URL for local pipeline API

Fix `kci-maintainer` tool

---

config/jobs-chromeos.yaml
config/runtime/fluster-chromeos.jinja2
config/scheduler-chromeos.yaml

This PR combines creates a new template `v4l2-decoder-conformance-chromeos` to execute Fluster test on ChromeOS.
It re-use the ChromeOS kernel module loading structure from Tast and Fluster parser script calling from v4l2-decoder-conformance test.
This PR depends on the template defined on https://github.com/kernelci/kernelci-core/pull/2617 PR

v4l2-decoder-conformance: Enable Fluster tests on ChromeOS

---

config/pipeline.yaml

Andy Gross (agross) hasn't been maintaining qcom for awhile now, but this tree is still valid & maintained by others.
Rename agross to qcom (URL doesn't change), and change the branch from `ci-next` (not touched in 4y) to the actively used one `for-next`

config/pipeline: rename agross to qcom

---

config/pipeline.yaml

Add default timeout and duration to the lava template instead of putting default values here in pipeline.
Pre-requisite PR: https://github.com/kernelci/kernelci-core/pull/2665

config: pipeline: Remove timeout and duration

---

config/pipeline.yaml

The omap tree was enabled in build-only category where minimal builds with mostly only default configs were enabled. The maintainer, Kevin wants the following:
the omap tree, it should only build for arm arch, and only build
omap1_defconfig omap2plus_defconfig and multi_v7_defconfig
So disable the build-only configs for omap tree and enable it only for those three configurations.
- The multi_v7_defconfig is the default config which is enabled for all trees by default.
- Add new entry for omap1_defconfig
- Add omap tree to already defined omap2plus config

config: pipeline: Enable omap tree for specific arm configs

---

docker-compose.yaml

As we create enormous load on builders and labs, we need to stop staging building all kernels except kernelci "manually" triggered kernel.
If anybody need to test on staging particular tree/branch, he need to use custom checkout API function in pipeline.

update(docker-compose): Restrict staging trigger to kernelci only

---

config/scheduler-chromeos.yaml

As discovered this test is very long running and blocking MesaCI tests and not really necessary on x86, so we can disable it on this type of devices.

fix(scheduler-chromeos): Disable tast-decoder-chromestack on x86

---

config/platforms-chromeos.yaml

Corsola cannot use kernel supplied with ChromeOS build for installing modules. Use current 6.10-stable kernel for that

fix(config): Fix "flasher" kernel for Corsola device

---

config/platforms-chromeos.yaml

The chromeos images are same. The tast images have data files now. Hence update their URL.
TODO: Correct the URL of images after images are generated from https://github.com/kernelci/kernelci-core/pull/2662.

config: platforms-chromeos: Update the URL of the tast images

---

config/pipeline.yaml
config/runtime/kbuild.jinja2

After introducing https://github.com/kernelci/kernelci-core/pull/2661 modules support detected in kbuild automatically, and manual option not needed anymore

cleanup(disable_modules): Cleanup option as it is not needed anymore

---

src/send_kcidb.py

Send runtime information to `misc` field to be used for post-processing.

src/send_kcidb: send `runtime` to `misc` field

---

src/send_kcidb.py

Update function to get job metadata to fetch lava job URLs and send them in `environment.misc.job_url` field for test submissions.

src/send_kcidb: send job URL for test submissions

---

src/send_kcidb.py

The log printing device tree compatible info was intended for development purpose. Hence, drop it.

src/send_kcidb: remove a log line for printing `compatible`

---

config/jobs-chromeos.yaml
config/result-summary.yaml
config/scheduler-chromeos.yaml

Linked to https://github.com/kernelci/kernelci-core/pull/2671
Rename the v4l2 decoder conformance tests using Fluster + Debian tests by replacing strings from `v4l2-decoder-conformance` to `fluster-debian`.
The main reason for the change is to make clear parallel with the `fluster-chromeos` tests wich are the same tests but uses chromeos as file system. This aims to ease future code maintainability of both test sets.

fluster-debian: Rename from v4l2-decoder-conformance to fluster-debian

---

config/jobs-chromeos.yaml

https://github.com/kernelci/kernelci-core/pull/2673 introduced some changes in the fluster_parser.py script, including an additional `--run` flag. 
Update the rootfs for fluster decoder tests on Debian, to incorporate the latest changes in the fluster_parser.py script and fix the  `fluster_parser.py: error: unrecognized arguments: --run` errors currently reported (see e.g.: https://lava.collabora.dev/scheduler/job/15780360#L10829).
The new rootfs image was generated using the [kernelci-core rootfs build action](https://github.com/kernelci/kernelci-core/actions/workflows/rootfs.yml).

config: jobs-chromeos: update rootfs for fluster tests on Debian

---

tools/kci-maintainer

Remove `git` as it's an unused package in the tool script.

tools/kci-maintainer: remove unused package

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Linked to: https://github.com/kernelci/kernelci-core/pull/2687
Add support for `Tast` tests in kernelci-pipeline targeting non-ChromeOs DUTs.
- Set a name to all `tast-decode` test params to re-use it both on Tast testing targeting ChromeOS and Debian.
- Introduce new job definitions for running Chromium's Tast tests on Debian rootfs.
- Add support for various decoding tests (H.264, HEVC, VP8, VP9) on Debian, targeting ARM64 platforms (MediaTek and Qualcomm).
- Extend the `tast` test suite by defining the Debian rootfs location, boot commands, and platform-specific configurations.
- Ensure compatibility with mainline, next, and Collabora Chrome OS kernel trees for testing.
- Update the `tast_tarball` field on `platforms-chromeos.yaml` to obtain a more recent tarball artifact. …

Tast-on-Debian: Add support for Tast tests targeting non-ChromeOs DUTs

---

config/jobs-chromeos.yaml
tests/validate_yaml.py

Add validator improvements and fix tast-debian configs

Fix tast debian

---

config/pipeline.yaml
config/scheduler-chromeos.yaml

Enable suspend and hibernation test. This patch depends on the https://github.com/kernelci/kernelci-pipeline/pull/743

Enable suspend and hibernation test

---

README.md

We have a bit outdated README. It actually needs more rework, but let's fix at least critical things.

fix(README): Remove dead links, add documentation for trigger cli options

---

src/send_kcidb.py
src/tarball.py

Depends on https://github.com/kernelci/kernelci-core/pull/2688
Set recently added checkout fields such as git commit tags, commit message, and flag denoting if the commit is at the tip of the branch.

src/tarball.py: set new checkout fields

---

config/pipeline.yaml

Fixes: https://github.com/kernelci/kernelci-core/issues/2686

config: Extend sashal/linus-next:linus-next builds

---

config/pipeline.yaml
config/scheduler-chromeos.yaml

Enable the discoverable devices probe kselftest on the MediaTek Chromebook platforms. This test will validate that the devices connected through USB or PCI on those platforms have been probed successfully. The devices are, namely, the camera on mt8183-juniper and mt8186-steelix, and the camera, wifi and bluetooth on mt8195-tomato.
Depends on https://github.com/kernelci/kernelci-core/pull/2577.
Fixes #579 .

Enable discoverable devices probe kselftest on MediaTek chromebooks

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

config: scheduler-chromeos: Enable graphics tasts and disable some tests

---

config/result_summary_templates/generic-test-results.html.jinja2
src/result_summary.py
src/result_summary/summary.py
src/result_summary/utils.py

- Generate links to lava jobs in the html summary outputs
- Use a node cache to reduce the amount of api requests

result_summary: Utility and performance improvements

---

src/trigger.py

Users might trigger tip of tree commit before trigger, ignore them and execute our own test set.

fix(trigger.py): Ignore commit created by user

---

config/scheduler-chromeos.yaml

This tasks taking too long time. Disabling until they are fixed.

fix(scheduler-chromeos.yaml): disable chromestack-debian tasks

---

src/send_kcidb.py

log_excerpt is too large and fills up truncated docker and k8s logs. Better to remove it from log output.

feat(send_kcidb.py): Remove log_excerpt from console logs

---

src/send_kcidb.py

Add `kbuild_internal_error` to missed test error codes as it means that kernel build failed and test couldn't run.

src/send_kcidb: add `kbuild` failure error code

---

src/send_kcidb.py

We map incomplete test node result to `ERROR` or `MISS` based on error code set. In some cases, we
have `null` as error code. Handle such situations by setting KCIDB test status to `None` as in this
situation we can't decide if the test actually could run or not.

src/send_kcidb: handle incomplete test nodes

---

config/jobs-chromeos.yaml

Initially I started investigating as it was failing only on Qualcomm targets. But as I investigated and made temporary fix in hardware_probe, I found out that this test fails on all the targets. Its just that its status gets marked as pass even though there are several warnings and missing directory structures for all other boards.
Let's disable this test as it only checks the hardware info which is closely tied with the chromeos. It doesn't run correctly on chromiumos.

config: jobs-chromeos: disable power.UtilCheck test

---

config/pipeline.yaml

Helen is working on clearning up android tree to share it with android team. To make results clean for the dashboard. Let's disable the kselftest tests for android tree.

config: pipeline: disable kselftest tests on android tree

---

config/pipeline.yaml

Add CIP tree and the relevant branches as requested in https://github.com/kernelci/kernelci-core/issues/2711.
Currently this PR only adds basic build support.
We'll also need to tailor what is build, and what is tested...
Whilst at it, add in a couple of minor code fixups.

Add CIP tree with default builds

---

config/pipeline.yaml

The "media_stage" and "media_tree" trees have now been unified to a single "media" tree, with "next" and "fixes" branches. Update the URL for the media tree and its branches accordingly.
See: https://lore.kernel.org/linux-media/20241007173146.6a35fa62@foz.lan/T/#u

config: pipeline: Update media tree URL and branches

---

config/jobs-chromeos.yaml

(Please check individual commits for description)

Disable graphics tasts

---

config/jobs-chromeos.yaml

video.PlatformDecoding.v4l2_stateless_av1_10bit* Tast tests started passing on cherry from the R130-16008.0.0 version of ChromiumOS. Disable the test for now and add reminder to revisit this at the next upgrade.

config: chromeos: Disable AV1 10-bit Tast tests on cherry

---

docker-compose-kcidb.yaml

Add postgresql proxy for further kcidb-bridge development

feat(docker-compose): Add postgres proxy for Google Cloud

---

docker-compose-kcidb.yaml
docker-compose.yaml
kube/aks/pipeline-kcidb.yaml
kube/aks/tarball.yaml
kube/aks/trigger.yaml
src/patchset.py
src/send_kcidb.py
src/tarball.py
src/trigger.py

We have already defined name for some of services for logging purposes, and we can add more names and use it for namespace-enabled key-value API storage.

feat(service-names): Add service names for some pipeline services

---

config/pipeline.yaml

The nommu_k210_defconfig config isn't present in two oldest stable kernels. Hence we get build errors. Add minimum version of the kernel to be 5.10 in which this configuration is present. I've only investigated this configuration option on stable kernels as this config is only being built on stable kernels.
close: https://github.com/kernelci/kernelci-pipeline/issues/857

config: pipeline: Add minimum kernel version for nommu_k210_defconfig

---

config/platforms-chromeos.yaml

ARM64 ChromeBooks are now using ChromiumOS R130, so we must point the platform definitions to the new Tast tarballs. x86 devices are still on R124 though, so they must keep using the current/old URL.

platforms-chromeos: use ChromeOS R130 for ARM64 devices

---

config/jobs-chromeos.yaml

Some tests no longer exist in ChromiumOS R130. Although it only affects ARM64 ChromeBooks for now, let's drop them entirely for the sake of consistency.
Fixes #843

config: jobs-chromeos: drop Tast tests not present in R130

---

config/pipeline.yaml

Add arm,arm64,x86_64,i386 allmodconfig builds.
As per Todd Kjos it is helpful to find most of build errors.

fix(configs): Add allmodconfig to mainline builds

---

config/pipeline.yaml

Let's just don't schedule anything on these boards without removing their entries. It would be easier to add them back. Disabled the following:
- raspberrypi,2-model-b
- brcm,bcm2836
- minnowboard-turbot-E3826
Close: https://github.com/kernelci/kernelci-pipeline/issues/861

config: pipeline: Disable always failing targets until they are fixed

---

config/pipeline.yaml
config/scheduler-chromeos.yaml

Add the devices-exist kselftest and enable it on mt8195-cherry-tomato-r2.
Depends on https://github.com/kernelci/kernelci-core/pull/2695.

Add devices-exist-kselftest and enable it on mt8195-cherry-tomato-r2

---

config/pipeline.yaml

CONFIG_FRAME_WARN is set to 1024 by default for arm. The allowed value for this is 0 to 8192. Let's increase it to 2048 to avoid getting the warning when stack size is more than default 1024. As all warnings are being treated as errors, our allmodconfig build fails on arm.
Close: https://github.com/kernelci/kernelci-project/issues/482

config: pipeline: Update CONFIG_FRAME_WARN for arm

---

src/lava_callback.py

Stacktrace observed in production:
File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
return await dependant.call(**values)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/kernelci/src/lava_callback.py", line 280, in callback
data = await request.json()
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 251, in json
body = await self.body()
^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 244, in body
async for chunk in self.stream():
File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 238, in stream
raise ClientDisconnect()
starlette.requests.ClientDisconnect
This should fix it and return error properly.

fix(lava_callback.py): Fix crash of lava_callback.py

---

src/lava_callback.py
src/send_kcidb.py

Some fields might be not present, as they are optional in model. Also add this field in custom checkout, even it is not mandatory, it is better to have it for consistency.

fix(send_kcidb): Do not crash if optional field is missing

---

kube/aks/kcidb-postgres-proxy.yaml

Add Google Cloud proxy for postgres to provide access to kcidb postgres database.

feat(kcidb-postgres-proxy.yaml): Add postgres gcloud proxy

---

config/jobs-chromeos.yaml

Let's reduce the number of trees on which we execute tast tests. The stable-rc and mainline are of interest to us only. This'll help us getting cleaner data and devices would be more free to execute other tests.
Close: https://github.com/kernelci/kernelci-pipeline/issues/878

config: pipeline: Run tast test only on mainline and stable-rc only

---

config/kernelci.toml
src/send_kcidb.py

In order to avoid using environment variables, use TOML file for KCIDB postgresql DB user password. Also, declare other existing args with `help` options in `cmd_run`.

src/send_kcidb: use kcidb postgresql password from TOML

---

config/pipeline.yaml

I've got a lot of arm64 boards in my lab but only Tritium is currently
hooked up.  Add a lot of the rest, there's some more i.MX8MP platforms
and Juno but adding these would conflict with the pending addition of 32
bit platforms so I'll come back and add them later.

config: pipeline: Add most of the arm64 boards in my lab

---

config/pipeline.yaml

Add compatible information for the Raspberry Pi 4.

config: pipeline: Add compatible information for Raspberry Pi 4

---

kube/aks/kcidb-postgres-proxy.yaml

We need to define service, to be able to contact it by FQDN.

fix(k8s/postgres-proxy): Fix deployment of postgres-proxy

---

src/send_kcidb.py

Print if it is a build or test node to make it easier to post process

src/send_kcidb: add node type information in logspec warning

---

config/jobs-chromeos.yaml

Update fluster debian tests KCIDB mapping to use `fluster.<file-system>.v4l2.*` syntax to unify the pattern with chromeos fluster test mapping.

config: update fluster debian test mapping

---

doc/config-reference.md
src/scheduler.py

We need capability to limit frequency of test/job execution, so particular heavy tests doesn't run on tree too often.
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/874

feat(scheduler): Implement frequency parameter

---

config/jobs-chromeos.yaml

This tests expects that the disk activity would be less 50%. But it is hard to guarantee this even in normal circumstances. I've confirmed that even in sanely booted chromiumos, there is disk activity. I've tried discussing it with the owner of this test, but no conclusion there as well. I've discussed with Denis and he agrees and suggest that we should disable this test.

config: jobs-chromeos: Remove LowPowerStateResidence

---

README.md
config/kernelci.toml
config/pipeline.yaml
doc/result-summary.md
kube/aks/kernelci-secrets.toml.example
src/send_kcidb.py

Related to https://github.com/kernelci/kernelci-core/pull/2638
- Rename configurations for `early-access` to `production`
- Remove `lava-collabora-early-access` lab

Rename early access configs

---

config/jobs-chromeos.yaml

Disable tests which have always been failing.
- The graphics stack for Mediatek is different on proprietary ChromeOS. Hence the test don't work on open-source ChromeOS. Disable all these test.
- Also disable all those tests which always fail because of missing dependencies. This includes camera clvk tests etc.

config: jobs-chromeos: Disable always failing tast tests on specific targets

---

config/pipeline.yaml

Enable the remaining arm64 boards in my lab.  There's also FVP but as an
emulated platform that needs much more substantial enablement.

config: pipeline: Add remaining arm64 boards in my lab

---

src/send_kcidb.py

Add recently enabled labs to LAVA lab mapping of lab name and URL to KCIDB bridge service. 
Also, add a warning print if lab URL mapping is not found for the specific lab.

src/send_kcidb: add new labs to LAVA labs mapping

---

config/pipeline.yaml

As suggested by Todd Kjos allmodconfig greatly help to find build errors and highly useful for stable-rc builds.

add(pipeline.yaml): Add allmodconfig to stable-rc builds

---

config/pipeline.yaml

As legacy builds disabled, we can use more build clusters.

feat(pipeline.yaml): Add more k8s clusters for builds

---

src/send_kcidb.py

Fix the below error while getting test job metadata:
```
File "/home/kernelci/pipeline/./src/send_kcidb.py", line 435, in _parse_test_node
job_metadata = self._get_job_metadata(test_node)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/kernelci/pipeline/./src/send_kcidb.py", line 358, in _get_job_metadata
data = self._get_job_metadata(parent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/kernelci/pipeline/./src/send_kcidb.py", line 363, in _get_job_metadata
elif 'lava' in data.get('runtime'):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

send_kcidb: Fix get job metadata

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/result-summary.yaml

As per internal discussion (ref: https://issuetracker.google.com/issues/371638530 ), we will not monitor `media` branch for fluster/tast v4l2 decoder tests neither for ChromeOS or Debian rootfs. We will keep monitoring `next` branch for fluster tests for now and evaluate its value later. In addition, ChromeOS will stay in `stable-rc_6.6` and eventually `stable-rc_6.12`, so we will keep monitoring this branch.

v4l2-decoder: Remove media tree monitoring, add stable-rc_6.6

---

docker/kcidb/Dockerfile

Some cases will require the kcidb bridge to interpret results from logspec before creating issues and incidents. Fix logspec to a specific commit so we can control when to upgrade it. This allow us to upgrade logspec in the same commit we upgrade kcidb bridge to keep them in sync.

docker/kcidb: fix logspec to a specific version

---

src/send_kcidb.py

If there is too many nodes it will significantly impact performance.

fix(send_kcidb.py): Limit nodes search to 1

---

src/send_kcidb.py

find() is paginated function using .count that might cause significant load on API server. Use more efficient findfast() call.

fix(send_kcidb.py): Use faster findfast function

---

src/kernelci_pipeline/logspec_api.py

After reviewing the current version of logspec we are using, all the errors parsed are of type code, so set culprit_code: True

src/logspec_api: set code_culprit True

---

src/kernelci_pipeline/logspec_api.py

For KCIDB it is better to re-submit the same object with the same id instead of querying to check if it exist already.
Remove the query and always submit a new issue.
Tested with local instance of kernelci-pipeline, submitting to KCIDB playground.

src/logspec_api: re-submit issues instead of querying

---

src/send_kcidb.py

Fix crash:
File "/home/kernelci/pipeline/src/base.py", line 69, in run
status = self._run(context)
^^^^^^^^^^^^^^^^^^
File "/home/kernelci/pipeline/./src/send_kcidb.py", line 717, in _run
self._get_test_data(node, context['origin'],
File "/home/kernelci/pipeline/./src/send_kcidb.py", line 529, in _get_test_data
test_node, build_node = self._parse_test_node(
^^^^^^^^^^^^^^^^^^^^^^
File "/home/kernelci/pipeline/./src/send_kcidb.py", line 453, in _parse_test_node
compatible = self._platforms[platform].compatible
~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'qcs6490'
And emit error instead.

fix(send_kcidb.py): Fix crash on missing platform

---

config/jobs-chromeos.yaml

tast: Fix tree monitoring for Tast tests
As per internal discussion, we will separate the handling of
Tast tests in 2 groups: decoder related Tast tests and other Tast
tests.
The Tast decoder related tests will be monitored on the following
branches:
- mainline
- collabora-chromeos-kernel
- stable
All other Tast tests will target:
- mainline
- stable-rc
With that, we revert the changes on the tree monitoring for non-decoder
tests made on https://github.com/kernelci/kernelci-pipeline/pull/897.
Signed-off-by: Denis Yuji Shimizu <denis.shimizu@collabora.com>

tast: Fix tree monitoring for Tast tests

---

kube/aks/scheduler-lava.yaml

Scheduler is able to filter out Runtimes it will submit Jobs to with a "--runtimes" option. The filter currently in use for Kubernetes deployment got out-of-sync with the LAVA Runtimes enabled in the Pipeline config.
This patch drops this option to fall back to the default behaviour which is submitting Jobs to all the Runtimes available in the Pipeline config.
Fixes: #925

Drop Runtimes filter on LAVA Scheduler in Kubernetes deployment

---

docker-compose.yaml

Scheduler is able to filter out Runtimes it will submit Jobs to with a "--runtimes" option. Even though the filter currently in use covers all the LAVA Runtimes available in the Pipeline config, using this filter may lead to missing some Job submissions in the future (if a new Runtime is not added to this list).
This patch drops this option to fall back to the default behaviour which is submitting Jobs to all the Runtimes available in the Pipeline config.
Docker-compose deployment is currently used on the Staging instance which limits its submissions by trigerring Jobs only on "kernelci" trees: https://github.com/kernelci/kernelci-pipeline/blob/54436dfff9786c4f5a827e94d8c9b7fe6fda12af/docker-compose.yaml#L147

Drop Runtimes filter on LAVA Scheduler in Docker-compose deployment

---

kube/aks/scheduler-lava.yaml

Reverts kernelci/kernelci-pipeline#937

Revert "Drop Runtimes filter on LAVA Scheduler in Kubernetes deployment"

---

docker-compose.yaml

Reverts kernelci/kernelci-pipeline#936

Revert "Drop Runtimes filter on LAVA Scheduler in Docker-compose deployment"

---

kube/aks/scheduler-lava.yaml

This patch adds missing LAVA Labs to the LAVA Runtime Scheduler in Kubernetes deployment.
This approach is prone to get desynced again in future and will be replaced by a "lab_type" filter for Schedulers as a long-term solution.

Align LAVA Runtimes in Kubernetes deployment

---

kube/aks/monitor.yaml
kube/aks/nodehandlers.yaml
kube/aks/pipeline-kcidb.yaml
kube/aks/regression.yaml
kube/aks/scheduler-k8s.yaml

Allocating (request) memory for pod will help to prevent unnecessary evictions.

fix(k8s): Allocate memory for pods

---

kube/aks/scheduler-lava.yaml
kube/aks/trigger.yaml
src/scheduler.py
src/trigger.py

1)pod memory allocation
2)scheduler fix due missing keys in node
3)trigger fix due tree returning tree during head retrieval

Various fixes 12 2024

---

config/pipeline.yaml

config: pipeline: Update CONFIG_FRAME_WARN for i386
CONFIG_FRAME_WARN is set to 1024 by default for i386. The allowed value
for this is 0 to 8192. Let's increase it to 2048 to avoid getting the
warning when stack size is more than default 1024. As all warnings are
being treated as errors, our allmodconfig build fails.
Example of a build failure:
https://kcidb.kernelci.org/d/build/build?var-datasource=edquppk2ghfcwc&var-origin=maestro&var-build_architecture=$__all&var-build_config_name=$__all&var-id=maestro:6772ceda423acf18d263ca6b&var-test-path=boot&from=now-100y&to=now&timezone=browser&var-test_path=&var-issue_presence=yes
Related https://github.com/kernelci/kernelci-pipeline/pull/870
Close https://github.com/kernelci/kernelci-project/issues/482
Signed-off-by: Muhammad Usama Anjum …

config: pipeline: Update CONFIG_FRAME_WARN for i386

---

config/pipeline.yaml

The goal is to run h26forge on platforms with h264 stateless decoders. So far only rk3399 and i.mx8mq got this kind of decoders. Only rk3399 is available in LAVA labs so limit the test to this device.

Add h26forge tests in pipeline and scheduler

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/scheduler-chromeos.yaml

Currently, most tests on Chromebooks run across all available tree/branch combinations. Restrict these tests to stable-rc and mainline trees to simplify monitoring while still identifying relevant regressions.

config: pipeline: Limit target trees/branches for Chromebook tests

---

config/pipeline.yaml

Now, as final step we try to enable kselftest-net collection. It might require future adjustments, as kernel options configuration.

upd(pipeline.yaml): Enable kselftest-net collection

---

config/pipeline.yaml
config/scheduler-chromeos.yaml

Some events have not specified kind, just kbuild-**somename**, as result when regression generated, with same name as kbuild event, it will trigger for example LAVA job with undesirable results.

fix(*.yaml): Add to event kind: kbuild

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

This patch set aims to:
- Add frequency limit for v4l2 video decoder tests as per Google's priority assignment.
- Re-enable `video.ChromeStackDecoder*` tests, since kernelci now has the `frequency` feature to limit the times the tests will be executed
- Split `video.ChromeStackDecoder.*` and `video.ChromeStackDecoderVerification.*` tests to have better granularity control of the `video.ChromeStackDecoder*` tests.

Tast: Set test priorities

---

config/pipeline.yaml

This PR describes the Genio 700 and 1200 EVK boards and enables the baseline test for them.
Additionally, it adds the 'lab-setup' configuration fragment to the `kbuild-gcc-12-arm64-job` in order to avoid deferred probe timeout issues that make the boot fail on those boards. The fragment is added in the generic arm64 build since it should avoid similar issues on other platforms as well.
Genio 700 EVK boot on linux-next: https://lava.collabora.dev/scheduler/job/17371995
Genio 1200 EVK boot on linux-next: https://lava.collabora.dev/scheduler/job/17372467

Enable baseline test for Genio 700 and 1200 EVK boards

---

config/pipeline.yaml
tests/validate_yaml.py

We need kselftest specific fragments for enabling kselftests properly.

upd(pipeline.yaml): Add kselftest fragment for x86/arm64 kbuild

---

docker/kcidb/Dockerfile
src/kernelci_pipeline/logspec_api.py
src/send_kcidb.py

This batch has 3 main parts:
* Handled special cases of logspec (kernel didn't started, bootloader didn't finished, prompt reached but we failed anyway)
* Code refactor of send_kcidb.py `_run()` function to make it easier to read/maintain
* Update nodes from FAIL to MISS when logspec detects infrastructure errors

send_kcidb/logspec_api: Improve issue/incidents handling (and refactor `_run()` )

---

src/send_kcidb.py

In some cases (broken nodes) we might crash on HTTP/4xx reply. Do not crash, still process events.

fix(send_kcidb.py): Do not crash if findfast fails

---

src/send_kcidb.py

We might send up to 200 events at once and it is causing problems at kcidb, let's limit temporary to 25 events at once.

fix(send_kcidb.py): Limit submission batch to smaller value

---

docker/kcidb/Dockerfile
src/kernelci_pipeline/logspec_api.py
src/send_kcidb.py

If the kernel booted, but maestro had set that to FAIL, change it to
PASS and create an issue with WARNING.

src/{send_kcidb,logspec_api}: report unclean boot as PASS

---

tools/example_api_lab.py

We need to add field that indicates this record is not processed yet by kcidb bridge.

fix(example_api_lab.py): Add mandatory field

---

config/pipeline.yaml

Example run: https://lava.collabora.dev/scheduler/job/17504017

config: pipeline: Enable baseline tests for Genio 350 EVK board

---

config/pipeline.yaml

Depends on https://github.com/kernelci/kernelci-core/pull/2786
Genio 700: https://lava.collabora.dev/scheduler/job/17514678
Genio 1200: https://lava.collabora.dev/scheduler/job/17514841

config: pipeline: Enable kselftest-dt on Genio 700 and 1200 EVK boards

---

config/pipeline.yaml

Depends on https://github.com/kernelci/kernelci-core/pull/2786.
Enable the kselftest cpufreq on Genio 700 EVK and Genio 1200 EVK.
Also enable the kselftest-cpufreq-suspend test on the Genio 700. The Genio 1200 fails to resume so the test is not enabled there for the time being.
Cpufreq  on genio 1200: https://lava.collabora.dev/scheduler/job/17514853
Cpufreq on genio 700: https://lava.collabora.dev/scheduler/job/17514861
Suspend on genio 700: https://lava.collabora.dev/scheduler/job/17514864

Enable cpufreq tests on Genio 700 and 1200 EVK

---

config/runtime/baseline.jinja2

Baseline tests will now just indicate reaching the state of successful boot. No other test case will be executed there (for the time being).
String: "Hello World!" as a mark of successful boot was chosen to comply with programming tradition but can be safely replaced with anything else (easily distinguishable from boot logs).

config: runtime: baseline: drop running dmesg.sh script

---

docker/kcidb/Dockerfile
src/kernelci_pipeline/logspec_api.py

do not generate issues for error_return_code since they are not
fatal, avoid noise.

src/logspec_api: ignore errors of type linux.kernel.error_return_code

---

config/pipeline.yaml

This is a minor refactoring of the base kselftest stuff in the pipeline,
in preparation for enabling more kselftests.
- config/pipeline.yaml: Factor generic kselftest rules into a separate block
- config/pipeline.yaml: Cover kselftest on -next by default

Refactoring for kselftest handling in pipeline

---

config/scheduler-chromeos.yaml

This jobs need optimization, they run over 7 hours and not completing.

upd(scheduler-chromeos.yaml): Disable debian decoder chromestack jobs

---

config/pipeline.yaml

Running them on every single board in my lab is probably excessive but
we can deal with that if it gets to be an issue.

config/pipeline.yaml: Enable the arm64 selftests in my lab

---

config/pipeline.yaml

We should really refine this to cover pKVM on at least some of the
systems that support this (currently just the i.MX8MP platforms), that
requires extra command line options and potentially some work on
reporting.

config/pipeline.yaml: Enable the KVM selftests on my arm64 boards

---

config/pipeline.yaml

Cover the timers selftests on a subset of the boards in my lab with a
bit more capacity.

config/pipeline.yaml: Enable timers selftests

---

config/pipeline.yaml

We need to test nvme-tcp offload feature, but until we integrate latest netdev trees, let's use this specific tree where latest version published.

upd(pipeline.yaml): Add aaptel tree for NVME-TCP offload

---

config/pipeline.yaml
docker-compose.yaml

This is an updated version of #673.
What I have changed:
- Rebase on top of recent `origin/main`.
- Use `https://lava.pengutronix.de` instead of `https://hekla.openlab.pengutronix.de`. They point to the same host, but the former is more descriptive.
- Add a `compatible:` entry to `platform:` `imx8mm-innocomm-wb15-evk:` since the other platforms have it.
Fixes: https://github.com/kernelci/kernelci-project/issues/387
Closes: https://github.com/kernelci/kernelci-pipeline/pull/673
This is just a minimalistic PR to revive the Pengutronix Lab at all. I will also open a follow-up PR soon that adds other devices from our lab, like `stm32mp157c-lxa-tac-gen1`, which is also mentioned in #673.

Enable Pengutronix lab

---

config/pipeline.yaml

Run the ALSA selftests on the boards in my lab with audio support, for a
lot of these it's just HDMI but still worth testing.  The PCM tests will
require UCM configuration to be useful on many of the boards with more
substantial audio but that's a rootfs issue and the tests should handle
it more or less gracefully.

config/pipeline.yaml: Enable ALSA selftests in my lab

---

config/pipeline.yaml

The ftrace selftests are basically CPU only so there's no a huge benefit
in running them on multiple boards until I start getting newer arm64
boards with relevant architecture features, pick some fast boards which
should also have enough RAM to boot the bigger kselftest kernels.

config/pipeline.yaml: Enable ftrace selftests in my lab

---

config/pipeline.yaml

Add coverage of the LTP smoke tests on 32 bit Arm using the BeagleBone
Blacks in my lab.

config/pipeline.yaml: Enable the LTP smoke tests on BeagleBone Black

---

config/pipeline.yaml

These are pure software tests so just run them on one board per
architecture, picking boards with a reasonable amount of capacity.

config/pipeline.yaml: Enable clone3 selftests in my lab

---

config/pipeline.yaml

The signal selftests are pure software tests, enable them on one board
with reasonable capacity for each architecture.

config/pipelie.yaml: Enable signal selftests in my lab

---

src/kernelci_pipeline/logspec_api.py
src/send_kcidb.py

In logspec_api, rename object_type to test_type, which are the supported types it can parse.
In send_kcidb, extract the test_type from the node.
Add kselftest to the list of types it supports.

src/{send_kcidb,logspec_api}: add suport for kselftest

---

config/pipeline.yaml

PREEMPT_RT was recently merged into mainline by Linus, so let's enable the tests in mainline trees.

config: pipeline: Enable rt_tests for mainline and next

---

config/pipeline.yaml

The futex selftests are software only so run them on one board for each
architecture, if I get access to newer microarchitectures it might make
sense to cover them but right now it's all pretty homeogenous.

config/pipeline.yaml: Enable futex selftests in my lab

---

config/pipeline.yaml

Another software only test, enabled on one board per architecture.

config/pipeline.yaml: Enable vDSO selftests in my lab

---

config/pipeline.yaml

A lot of the kselftests require config options which are enabled in their
config fragments and incorporated into the kselftest build but currently we
only build that for the kselftest tree, meaning that we don't get the test
coverage for these. Enable build for the main upstream trees too so we can
run these tests.

config/pipeline.yaml: Build the kselftest fragment for more trees

---

config/pipeline.yaml

This is a software only suite, enable it for one board on each
architecture in my lab.

config/pipeline.yaml: Enable landlock selftests in my lab

---

config/jobs-chromeos.yaml
config/pipeline.yaml
config/scheduler-chromeos.yaml

Add the ChromiumOS kernel tree (branches 5.4 to 6.12) and define new Clang kbuild jobs for both ARM64 and x86_64 Chromebooks.

config: chromeos: Add ChromiumOS tree and Clang kbuild jobs

---

config/pipeline.yaml
docker-compose.yaml
src/base.py
src/lava_callback.py
src/tarball.py
src/trigger.py

This patch series adds support for dynamically updated branch names in the Pipeline config. It's required for [NIPA system](https://github.com/linux-netdev/nipa/wiki/Netdev-CI-system) integration.
Please see also the details descriptions in specific patches.

Use dynamic branch triggers

---

config/pipeline.yaml
config/runtime/blktests-ddp.jinja2

This is initial template, fixed for now to specific hardware required for NVME-TCP DDP offload.

add(blktests-ddp.jinja2): Add blktests nvme-tcp offload initial template

---

config/pipeline.yaml

We update URL where branches retrieved and also enable blktest-ddp (nvme-tcp offload) to netdev testing.

Minor updates for netdev git and ddp testing

---

src/send_kcidb.py

Today the Maestro lab is sent through the 'runtime' field, but that name is not that great for labs. Let's add a 'lab' field, but wait a bit to remove the 'runtime' field, so we can transition some KCIDB queries without any trouble.

send_kcidb: add 'lab' field to misc data submitted

---

config/pipeline.yaml

These are mostly CPU based, there will be benefits running them on more
platforms with different CPU types.

config/pipeline.yaml: Enable perf_events selftests in my lab

---

config/pipeline.yaml

Depends on https://github.com/kernelci/kernelci-core/pull/2786
Example run: https://lava.collabora.dev/scheduler/job/17513959

Enable wifi-basic test on the Genio 700 EVK

---

config/pipeline.yaml

Depends on https://github.com/kernelci/kernelci-core/pull/2786.
Genio 700: https://lava.collabora.dev/scheduler/job/17515212
Genio 1200: https://lava.collabora.dev/scheduler/job/17515224

Enable device error logs kselftest on Genio 700 and 1200 EVK boards

---

kube/aks/scheduler-shell.yaml

NIPA operates using shell runtime, adding scheduler for that

add(scheduler-shell.yaml): Add new k8s scheduler for shell

---

src/trigger.py

We should not overwrite original build config, so on next iteration we fetch fresh NIPA branch.

fix(trigger.py): Fix build config parameter overwrite

---

src/trigger.py

This reverts commit 34a184d0032ace2994bcc9210d65e5af15fa893d.

Revert "fix(trigger.py): Fix build config parameter overwrite"

---

src/send_kcidb.py

KCIDB need to be able to see full config name, not just defconfig.
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/1011

fix(send_kcidb.py): Send full config name to KCIDB

---

config/pipeline.yaml

More software only tests, enabled on one board per architecture.

config/pipeline.yaml: Enable the seccomp selftests in my lab

---

config/pipeline.yaml

Another simple pure software selftest, run on Beaglebone Black and pick
an arm64 board with capacity.

config/pipeline.yaml: Run the capabilities selftests in my lab

---

config/pipeline.yaml

Yet more software only selftests, enabled on one board per architecture.

config/pipeline.yaml: Add user_events selftests in my lab

---

src/tarball.py
src/trigger.py

This patch creates copies of BuildConfig objects so that the initial values are not changed. This way dynamic branch triggers (external JSON resources) are not replaced with static branch names after first request.
Fixes: https://github.com/kernelci/kernelci-pipeline/issues/1047

Fix overwriting build config for dynamically changing branches

---

config/pipeline.yaml

KUnit tests are enabled by default on all trees. Since a different set of initial tests will be enabled on the chromiumos tree, disable KUnit tests for now.

config/pipeline.yaml: Disable KUnit tests on chromiumos tree

---

config/pipeline.yaml

Add job stanzas for a lot of LTP suites we don't already cover and use the
spare capacity we have on Beaglebone Black in my lab to run a lot more of
LTP. Since the boards use NFS root, have only one CPU and limited memory
there are a bunch of suites that aren't appropriate but this is most of
them.

config/pipeline.yaml: Enable more LTP on my Beaglebone Blacks

---

config/jobs.yaml
config/runtime/nipa-update.jinja2

1)Make sure aaptel tree doesnt send results to NIPA
2)Make sure we append results to json, not overwrite

Nipa fixes

---

config/trees.yaml

Trees added by this PR were requested to be tested with `fluster-debian` Jobs. Currently there are up to 7 of them (depending on the hardware the tests are executed on):
```
$ grep -r "job: fluster.debian" config/ | sort -u
scheduler-chromeos.yaml:  - job: fluster-debian-av1
scheduler-chromeos.yaml:  - job: fluster-debian-av1-chromium-10bit
scheduler-chromeos.yaml:  - job: fluster-debian-h264
scheduler-chromeos.yaml:  - job: fluster-debian-h264-frext
scheduler-chromeos.yaml:  - job: fluster-debian-h265
scheduler-chromeos.yaml:  - job: fluster-debian-vp8
scheduler-chromeos.yaml:  - job: fluster-debian-vp9
```
All these Jobs are triggered by a KBuild Event `kbuild-gcc-12-arm64-chromebook` which has no run restrictions (`rules:` section) as of writing this comment.
Checkout Events on newly …

config: trees: Add media-committers tree with next and fixes branches

---

config/platforms.yaml
config/scheduler.yaml

The entry for Juno is not actually causing any jobs to be scheduled on the
Juno in my lab since due to a hardware failure that stops EDK2 working it
has fixed u-boot firmware and is registered as 'juno-uboot'. Since KernelCI
matches on this name using 'juno' results in no jobs being scheduled. Fix
that, adjust to say 'juno-uboot'. A 'juno' entry can be re-added if we get
any fully flexible Junos.

config: Fix name of juno-uboot

---

config/platforms.yaml
config/scheduler.yaml

This is an ARMv5 board so runs multi_v5_defconfig and needs an armel rootfs.

config: Add AT91SAM9G20-EK

---

config/jobs-chromeos.yaml

The current rules override in the Tast decoder test job definition only considers the minimum kernel version, ignoring the existing tree-specific rules. Reintroduce the tree rules.

config: jobs-chromeos: Fix rules override for Tast decoder tests

---

src/lava_callback.py

Sometimes we want to retry test job, AND also
retry associated "child" jobs, such as nipa-update.

(lava_callback.py): Add job-filter

---

src/lava_callback.py
src/monitor.py
src/scheduler.py
src/test_report.py
src/trigger.py

A bit of clean up, as part of a review of the kernelci. imports I was doing.

services: remove unused imports

---

config/jobs-chromeos.yaml

This patch reverts:
1c2b9d71f7788b3bce1a0b9976bd49f7b8652ca9
which was introduced in PR #812
These Tast tests are expected to be run on ChromeOS, not Debian-based rootfs. With this change Job template "tast-debian" is not used in the Maestro Pipeline config anymore.

config: Drop remaining Tast Debian bits

---

config/scheduler.yaml

Since the NFS issues have a fix on their way to -next offload some of the
longer running test jobs from other boards to the Raspberry Pi 3+s in my
lab to balance out capacity. The boards concerned are all four cour Cortex
A53s so there should be no meaningful coverage impact when everything is
running.

config/scheduler.yaml: Offload some arm64 jobs onto Raspberry Pi 3+

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Lower the frequency of chromiumos builds to 1/day, both for GCC-12 and Clang-17 builds.

config: Lower the frequency of chromiumos builds to 1/day

---

config/trees.yaml
src/monitor.py
src/scheduler.py
src/send_kcidb.py
src/tarball.py
src/trigger.py

Some trees need to be limited to listed architectures. Add option to config, that will allow to restrict build variants, and when present create in checkout node architecture_filter parameter.

(architectures): Add option to limit build variants to specific architectures

---

src/monitor.py
src/scheduler.py
src/send_kcidb.py
src/tarball.py

If we got HTTP error, likely we lost subscription due remote server restart. Instead of crashing, try to resubscribe several times, with delay, to allow remote server restart.

(events): Add re-subscribe mechanism

---

config/platforms.yaml

In some places platform listed as rk3399-rock-pc,
but in some rk3399-roc-pc. Let's have both for now.

(config) Add one more platform, roc/rock confusion

---

config/jobs.yaml
config/scheduler.yaml

These are software only tests, run them on one board per architecture in
my lab.

config: Enable the ublk selftests

---

tests/validate_yaml.py

Commit c00b656 ("(tests/validator) Improve build_configs verification") added validation of the `tree` and `branch` attributes to the `build_configs` property.
However, if a referenced tree is missing, the validation code will terminate with an error as the variable used is not a dictionary but a string type, and as such, the `.get()` method cannot be called.
Thus, fix which variables are referenced and the order of validation for the `tree` and `branch` attributes to validate their presence within a given tree object first.
While at it, update the accompanying code comment.
Related:
- https://github.com/kernelci/kernelci-pipeline/pull/1104

Fix validation for trees within build_configs

---

config/jobs.yaml
config/trees.yaml

Add the official PCI tree such that tests can be run on the `next` branch for the following architectures:
- x86_64
- arm64
- arm
This aims to increase and improve test coverage as part of the PCI sub-system development efforts.

Add official PCI tree to run tests on the next branch

---

config/jobs-chromeos.yaml
config/platforms-chromeos.yaml
config/scheduler-chromeos.yaml

Enable boot tests on the chromiumos tree and run them on all available Chromebooks. Run the tests on Debian for starters.

config: Enable boot tests on chromiumos tree

---

config/jobs.yaml

Sort the list of trees alphabetically for build-only jobs, and add a note about preserving the sort order.
Related:
- https://github.com/kernelci/kernelci-pipeline/pull/1100

Sort list of trees alphabetically for build-only jobs

---

src/send_kcidb.py

As Qualcomm use Maestro to submit results, we need to allow kcidb bridge to process their records.

(send_kcidb.py) Add qualcomm to allowed users

---

config/trees.yaml

KernelCI will schedule builds for each currently supported architecture for each tree. This is also the default behaviour if no specific architecture filters are provided. Such builds can include architectures that are of no interest to the owner of a given tree, or the code that the tree carries would not be intended to run on some architectures.
For example, for an ARM64 development tree, testing on an x86_64 or RISC-V platform is potentially of no use to the developers, even if errors were reported. However, running these extra builds impacts the available resources (CPU, memory, I/O, etc.) and the time it takes to allocate a build machine to run builds and tests on.
Thus, limit each tree to the most suitable architectures (on a base-effort basis). This can include specific target …

Add architectures filter to limit builds to relevant platforms only

---

config/platforms-chromeos.yaml
config/scheduler-chromeos.yaml

Add support for brask, nissa, hana and cherry-r3 Chromebooks. Enable baseline/baseline-nfs tests only for starters.

Add brask, nissa, hana and cherry-r3 Chromebooks

---

config/trees.yaml

Commit cfe037a ("Add architectures filter to various trees") added architectures filters to a variety of trees and, while doing so, also introduced a utility tree called `_base`, which is then used to provide configuration anchors to facilitate reuse.
However, this utility tree will also trigger jobs to be run, which is not desired, as these extra anchors are only used to reduce configuration duplication.
Thus, move the `base`, `base-standard`, and `base-arm` anchors into the `_anchros` section, which will only be used to assemble the configuration and, as such, will prevent any extra jobs from being run.

Move entries for anchors correctly into the _anchors section

---

.github/workflows/main.yml
requirements-dev.txt

The support for the Ubuntu release **20.04** is being retired, and runners that use it are to be deprecated, too. See:
- [GitHub Actions: Ubuntu 20 runner image brownout dates and other breaking changes](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes)
- https://github.com/actions/runner-images/issues/11101
Related:
- [GitHub Actions: Ubuntu-latest workflows will use Ubuntu-22.04](https://github.blog/changelog/2022-11-08-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04)
- [GitHub Actions: Ubuntu-latest workflows will use Ubuntu-20.04](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04)
> [!NOTE]  
> Note that Canonical will not retire 20.04 and mark it as …

Update Ubuntu release to 22.04 for GitHub Actions

---

config/trees.yaml

Add a new `for-linus` branch to the PCI tree configuration.
This branch is often used as a step before sending a Pull Request to Linus with fixes from the PCI tree that need to be applied during the development cycle of a new kernel version release.
Thus, it's prudent to run tests against it to increase coverage and boost confidence in the changes it carries.

Add new branch to the Linux PCI tree configuration

---

requirements-lava-callback.txt

We have now requirements buried in the docker directory, which is planned to be deleted. Let's move it to root directory. We still need them for kernelci-core recipes.

Add python requirements to the root

---

config/platforms-chromeos.yaml

[1] introduced branch rules for every Chromebook platform, for the chromiumos, stable and stable-rc trees. Add branch rules for remaining target trees tested on Chromebooks too, namely
collabora-chromeos-kernel, mainline and next.
[1] https://github.com/kernelci/kernelci-pipeline/pull/1090

config: platforms-chromeos: Add branch rules for mainline, next and collabora-chromeos-kernel trees

---

config/trees.yaml

Ensure that Android trees run on the following architectures:
- `x86_64`
- `i386` (32-bit x86)
- `ARM64`
- `ARM`
- `RISC-V`
- `UM` (User-Mode Linux)
Note that at this time `MIPS` architecture is not included.

Fix architectures filter for Android tree

---

config/trees.yaml

Add a dedicated KernelCI branch called `for-kernelci` to the Linux PCI tree configuration.
This will open the possibility for more testing to be carried out using this new branch, especially as the previously added `next` and `for-linus` branches are somewhat special to the official PCI tree, and should not be used for ad hoc tests, etc.
This new branch will also be excluded from the Intel 0-day Bot tests.
While at it, update the existing `linux-pci` property to add the name of the branch to it.
Related:
- https://github.com/intel/lkp-tests/pull/507

Add dedicated KernelCI branch to the Linux PCI tree configuration

---

config/jobs.yaml
config/pipeline.yaml
config/platforms.yaml
config/scheduler.yaml
docker-compose.yaml

The lab was not migrated to new pipeline, lets do it.
The callback token is still the same as used with the old pipeline configuration.

Re-enable kontron's lab

---

config/jobs.yaml
config/scheduler.yaml

The upstream issues which prevented kselftest-mm runs on arm have been
fixed so let's enable the tests, use Avenger96 since it's quite fast and
has a relatively large amount of RAM.  Standard two level page tables
don't support hugepages on 32 bit.

config: Enable mm selftests on Avenger96

---

config/platforms.yaml

Extend pipeline to support additional Qualcomm platforms:
- qcs8300-ride
- qcs9100-ride

(platforms.yaml) Add Qualcomm platforms qcs8300 and qcs9100

---

config/jobs-chromeos.yaml
config/platforms-chromeos.yaml

Enable testing for the chromeos-6.12 branch of the ChromeOS kernel on all available Chromebooks.

config: Test chromiumos/chromeos-6.12 on all Chromebooks

---

config/jobs-chromeos.yaml
config/jobs.yaml
config/scheduler.yaml
config/trees.yaml

Update jobs for the OMAP tree:
- Only run jobs on the 32-bit ARM
- Remove no longer needed `omap1_defconfig` job
- Remove from some jobs e.g., ChromeOS, Chromebook, etc.
Additionally, limit the `omap2plus_defconfig` job to only run for the OMAP tree.

Update jobs for the OMAP tree

---

config/jobs.yaml

This is initial commit to return CIP specific fragments, and also will serve as verification that everything works right for this fragments.

(jobs.yaml) Add back as example cip:// config fragment

---

src/send_kcidb.py

Some nodes are not eligible to be sent to KCIDB,
for example custom user supplied nodes, but we need to mark them as processed, otherwise they will keep wasting cpu cycles and appear in new findfast queries.

Mark nodes as processed even if empty

---

config/jobs.yaml

The OMAP tree target architecture is 32-bit ARM, so running a KUnit job for the `x86_64` architecture for this specific tree does not make much sense and unnecessarily consumes resources.
Thus, turn off this specific KUnit job for the OMAP tree.
> [!NOTE]  
> The architecture filters added to a specific tree configuration are not currently applied against jobs other than kernel builds.

Don't run KUnit job on x86_64 architecture for OMAP tree

---

config/scheduler.yaml

To execute kbuild, it needs to be added to scheduler entries.

Add kbuild-gcc-12-arm64-chromebook-media-committers to scheduler entries

---

config/scheduler.yaml

To execute the `kbuild-clang-17-arm` build job, it has to be scheduled.
Thus, add a missing scheduler entry for it.

Ensure that kbuild-clang-17-arm build job is scheduled

---

src/send_kcidb.py

Due deprecation of field 'valid' in kcidb schema, we lost trigger condition when 'valid' == false was triggering logspec. We can trigger same as on tests, by status == FAIL, which was equivalent to `valid` retrieved by status map.

(send_kcidb.py) Fix logspec trigger by status

---

config/jobs.yaml
config/scheduler-chromeos.yaml
config/scheduler.yaml

As we're enabling code coverage using GCOV in KernelCI, we must ensure we have a kernel with the corresponding options enabled using the `coverage` fragment, and also run some tests using this kernel.
The LTP tests we run on x86 Chromebooks are good candidates for helping during developement.

Add kbuild job with coverage enabled and run tests using this kernel

---

src/send_kcidb.py

Infrastructure errors were previously mapped to MISS state in KCIDB while all such cases should be marked as ERROR.
Fixes: #1154

send_kcidb: Map infrastructure TestJob errors correctly

---

docker-compose-production.yaml
src/lava_callback.py

As this service is actually just a FastAPI app, only the use of the uvicorn logger can allow us to print messages.
Take this opportunity to replace undifferenciated `print`s with proper logs w/ severity and set log level to `debug`` by default.

src: lava_callback: improve logging

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Add fault injection configs to chromeos and schedular yamls

Define fault injection job

---

config/jobs.yaml

We now have GCOV-enabled LTP test runs, which require a new rootfs in order to upload artifacts directly from the DUT in LAVA.

config: jobs: use new LTP rootfs

---

src/lava_callback.py

Test jobs might need to upload artifacts directly from LAVA (this is needed e.g. for GCOV data when checking for code coverage), but we currently have no way to add those artifacts to the corresponding node.
Add such a feature in a rather generic way, so jobs can provide both the artifact name and its URL through a specially-formatted result entry:
`artifact-upload:<artifact name>:<artifact URL>`
Therefore, all test results starting with `artifact-upload:` will be processed and stored in the corresponding node's `artifacts` dict, with `<artifact name>` being the entry key and `<artifact URL>` being its value.
Depends on #1159 & https://github.com/kernelci/kernelci-core/pull/2878

src: lava_callback: handle artifacts uploaded from test jobs

---

src/send_kcidb.py

After we switched to REST interface, we can afford bigger batches, also let's add long time pending optimizations, to reduce CPU use, and to allow events to process data naturally.

(send_kcidb.py) Optimize KCIDB bridge

---

src/tarball.py
src/timeout.py

As mentioned in #1163 the current timeout services (`timeout`, `holdoff` & `closing`) cause unwanted state transition for *child nodes* of timed-out nodes.
This PR reworks those services to avoid such unwanted transitions by **never** modifying the state of child nodes while transitioning a given node to a different state, making such transitions more reliable and predictable and allowing us to use this information more widely.
Moreover, handling of `checkout` nodes was special-cased for no good reason, so let's demote it to a not-so-special node, reducing a bit the overall complexity.
Fixes #1163

Fix timeout services & state machine

---

config/trees.yaml

For some reason the stable-rc tree definition references itself.  I'm
surprised this is valid, and can't imagine it's helpful (I do note that
we're not currently generating test jobs for stable-rc...), so let's
remove it.

config: trees: Remove self reference for stable-rc

---

config/pipeline.yaml

Purge an entry to `runtimes` section for Qualcomm
lab as lab is adopting KernelCI 2.0 model.

config/pipeline.yaml: Purge lab config for Qualcomm

---

config/scheduler-chromeos.yaml
config/scheduler-cip.yaml
config/scheduler.yaml

Until now, test jobs were triggered when corresponding `kbuild` nodes
were changed to `result: pass`. This made sense as those nodes would
immediately and always transition to state `done` upon completion.
As they're now going through the `available` state when successful, we
can use this event instead for triggering test jobs.
Make this change throughout all scheduler configs, improving
`scheduler-chromeos` through the use of a corresponding anchor in the
process.
Depends on https://github.com/kernelci/kernelci-core/pull/2882

config: scheduler*: change job trigger for available kbuilds

---

config/jobs.yaml
config/scheduler.yaml

These are again small, software only tests.

config: Enable the fchmodat2 selftests

---

config/jobs.yaml
config/scheduler.yaml

The time namespace selftests are simple software only tests.

config: Enable the timens selftests

---

config/jobs.yaml
config/scheduler.yaml

The configuration has a single baseline job for the 32 and 64 bit Arm
boards in the Baylibre lab, tied to the 32 bit Arm builds.  This
obviously doesn't work for the 64 bit boards, resulting in inconclusive
boots as the 64 bit boards don't understand zImage.  Split into a
separate baseline job like the other labs.

config: Split 32 and 64 bit Arm jobs in the Baylibre lab

---

config/jobs.yaml
config/scheduler.yaml

This does have some hardware dependencies, the number and kind of
physical breakpoints can vary.

config: Add breakpoints selftest

---

config/jobs.yaml
config/scheduler.yaml

Protected KVM is an arm64 KVM feature which provides for hypervisor
protection of some VMs, enable testing of this mode where supported.
The main requirement currently is for GICv3.

config: Run the KVM selftests in pKVM on arm64 systems that support it

---

doc/connecting-lab.md
doc/developer-documentation.md
doc/pipeline-details.md

We no longer transition successful `kbuild` nodes directly to `done` state, but go through `available` first. This state triggers test jobs' creation, while we can schedule post-processing jobs when the node finally reaches the `done` state` (once every test job is complete, or the timeout is reached).
Ensure the documentation (especially the examples) reflects the current design.

doc: update to reflect latest changes in state transitions

---

config/runtime/kbuild.jinja2

In Python, os.system() returns the exit status in a platform-specific format. On Unix-like systems, it returns the exit status shifted left by 8 bits. Here's what's happening:
- My shell script exits with code 1 (build failure)
- os.system() returns 256 (1 << 8)

(kbuild.jinja2) Get return code properly

---

config/platforms.yaml
config/scheduler.yaml

The SoC name changed from the original board mainly.

config: Fix cut'n'paste errors in the VisionFive2 integration

---

kube/aks/scheduler-lava.yaml

This Runtime has been in use only by Maestro Staging instance so far (docker-compose-based deployment). Add it to Kubernetes deployment defaults to enable LAVA TestJob submissions from Maestro Production instance as well.

kube: aks: add lava-pengutronix runtime

---

config/trees/linux-pci.yaml

Branch "for-kernelci" does not exist for this tree.

config: trees: Drop nonexistent Build configuration for linux-pci tree

---

config/trees/linux-pci.yaml

This reverts commit 346a543548cdcb7462d2bcd4f6af0ebe1b139724.
Branch "for-kernelci" is added on demand and its temporary absence shouldn't be considered as a permanent removal.

Revert "config: trees: Drop nonexistent Build configuration for linux-pci tree"

---

config/jobs.yaml
config/scheduler.yaml

Software only tests, enabled for one board per architecture in my lab.

config: Enable LSM selftests

---

config/jobs.yaml
config/scheduler.yaml

The sync selftests are software only, this isn't terribly actively
worked on.

config: Enable sync selftest

---

config/jobs-chromeos.yaml
config/jobs.yaml

Update to the 20250617.0 rootfs build, which switches to (and ensures
that we stick to) the LTP 20250530 release tag.

config: Update to LTP 20250530 release

---

config/scheduler.yaml

Currently we have fairly weak coverage of LTP on arm64, expand this
using my lab.

config: Expand LTP coverage on arm64

---

config/scheduler.yaml

The LTP syscalls suite is one of the larger ones, put it on some faster
boards in my lab (with multiple cores so we'll get a bit of a speedup
when the parallel workers stuff lands).

config: Enable LTP syscalls suite

---

docker-compose-lava.yaml

Docker image for Service "lava_callback" had previously been built on-demand during Staging instance deployment. This has been changed in the new Staging deployment workflow.
This patch uses prebuilt Docker image for "lava_callback" Service. Docker image build context will be dropped in the future if it's deemed unnecessary from development point of view as well.

docker-compose-lava: Comply with the new Staging deployment process

---

config/scheduler.yaml

We currently have no LTP coverage for ARMv5, but we can and do build
rootfs images for Debian's armel architecture.  Start making use of
these to provide LTP coverage for this architecture variant using the
AT91SAM9G20-EK in my lab.

config: Enable LTP smoketest on AT91SAM9G20-EK

---

config/scheduler.yaml

Especially when the stable releases come out the Avenger96 can build up
quite a backlog, move a lot of the smaller single threaded jobs over to
Beaglebone Black which has more capacity in my lab.

config: Move some jobs off Avenger96

---

config/jobs.yaml
config/scheduler.yaml

- config: Add Radxa Orion O6
- config: Enable more tests on the Orion O6

config: Enable more tests on the Orion O6

---

src/send_kcidb.py

In order to keep build results consistent for dashboard and maestro, send timed-out builds with `MISS` status to KCIDB.

src/send_kcidb: send timed-out builds

---

config/scheduler.yaml

- config: Focus scheduling of KVM tests in my lab
- config: Use standard event to trigger kvm-unit-tests jobs

KVM job scheduling improvements

---

config/jobs.yaml

The Kirk LTP runner which we are using supports parallel execution of
tests, this is fortunately able to identify and appropriately handle
tests that have to be run single threaded making it relatively easy to
use.  It does unfortunately make the console output a bit less helpful
but they're still there, and Kirk does report per-test logs.
With the test-definitions integration we can specify the number of
workers as "max" in order to allow one worker per CPU in the system, do
that by default.  There is some risk that tests might interfere with
each other and become less stable, if this becomes an issue we can
revisit and use this only for suites that particularly benefit.

config: Enable parallel LTP execution

---

config/runtime/kunit.jinja2

Nodes are created in `running` state by default. Recent changes to the API helper functions copy the `state` field from the node instead of setting it to `done` by default, meaning result nodes stay `running` until they time out.
Fix this by making those nodes `done` right from the beginning.

config: runtime: kunit: ensure result nodes are in "done" state

---

config/platforms.yaml
config/scheduler.yaml

Toradex have been kind enough to send me an AM62 Mallow system, enable
some basic tests on it in my lab.

config: Enable AM62 Mallow in my lab

---

config/runtime/kunit.jinja2

Due to changes in the top-level `python` template, the kernel source is now only downloaded and unpacked for `kbuild` nodes. Let's add the needed bits to `kunit` jobs so we get the full source as well.
Depends on https://github.com/kernelci/kernelci-core/pull/2909

config: runtime: kunit: download kernel source in job

---

src/timeout.py

Do not mark timed-out node as "incomplete" if the result is set to "fail" or "skip".
Fixes: fe42dd5 ("src: timeout: make state transitions more predictable")

src/timeout: fix logic marking nodes as "incomplete"

---

config/jobs.yaml
config/trees.yaml
config/trees/qcom-next.yaml

Integrates the qcom-next tree to enable CI/CD workflows on the 'next' branch to 
ensures validation of changes and improves stability across development iterations.

Add qcom-next tree to run CI/CD on the next branch

---

config/jobs.yaml
config/scheduler.yaml

The AM62 Mallow board in my lab has a TPM so is able to run the TPM2
selftests, use it to enable them.  I imagine some of the Chromebooks
could also do this.

config: Enable TPM2 selftests

---

config/scheduler.yaml

The Orion O6 is a v9 system so there's some benefit in running tests
that might exercise new architecture features.

config: Run more tests on Orion O6

---

config/jobs.yaml
config/scheduler.yaml

The sync selftest is a software only test, enable it on a few boards in
my lab.

config: Enable sync selftests

---

config/jobs.yaml
config/scheduler.yaml

The ring buffer selftest is another software only test, enable it on a
couple of boards in my lab.

config: Enable ring-buffer selftest

---

config/jobs.yaml
config/scheduler.yaml

Another software only test enabled on one board per architecture in my
lab.

config: Enable memfd selftests

---

src/lava_callback.py

`jobfilter` entries can now be suffixed with a `+` (see https://github.com/kernelci/kernelci-core/pull/2930), meaning "this job and all of its child nodes are allowed". We need to take this into account by dropping this suffix if it's present when checking whether the listed job actually exists.

lava_callback: take into account jobfilter suffix if needed

---

src/send_kcidb.py

Make API URL dynamic in `maestro_viewer` field for KCIDB submissions.

KCIDB bridge: fix `maestro_viewer` URL

---

src/trigger.py

Build configurations list will not be known up front when external configuration files are enabled in Maestro. Dropping `build_configs` filter will allow simplifying Trigger Service logic taking into account only parameters that are still relevant.

Switch Trigger Service main loop data structure

---

requirements-lava-callback.txt

This upgrade is required for migrating base Pipeline image to Python 3.12.

requirements: Bump uWSGI for LAVA Callback

---

config/jobs-chromeos.yaml
config/jobs.yaml
config/scheduler-chromeos.yaml
config/scheduler.yaml

Our only planned user for code coverage analysis is the ChromeOS kernel team, so this PR fully reworks the coverage-enabled builds and test jobs.
To sum things up, the current, generic x86 kernel build is replaced by 4 distinct builds:
* 2 for Intel & AMD ChromeBooks (x86)
* 2 for Qualcomm & Mediatek ChromeBooks (arm64)
Those builds use the following config fragments on top of the usual ones:
* `coverage` for enabling GCOV support in the kernel
* `kselftest` so we can run the corresponding tests on those kernels (will be enabled as a follow-up PR)
* `crypto` so those kernels can also execute the `ltp-crypto` job
All LTP jobs currently executed on the ChromeOS kernel are now also scheduled for those new builds, replacing the previous LTP scheduler entries (those were using the generic x86 …

config: rework all coverage-enabled jobs

---

config/logger.conf
docker-compose.yaml
src/job_retry.py
src/scheduler.py

Depends on https://github.com/kernelci/kernelci-core/pull/2927
The pipeline service will listen to failed or incomplete jobs and submit a retry for it.

Implement service to submit job retry

---

tools/extract_compatible.py

This patch fixes the directory of the linux sources files, for when the extract_compatible script is called from a different directory than tools/

tools/extract_compatible: Fix extract_compatible path for linux sources

---

config/jobs-cip.yaml
config/platforms-cip.yaml
config/scheduler-cip.yaml

CIP boards list is from
https://lava.ciplatform.org/scheduler/alldevices/active

(config/cip) Add active cip boards

---

src/timeout.py

Fix the below error:
```
File "/home/kernelci/pipeline/src/timeout.py", line 119, in _get_available_nodes
'holdoff__lt': datetime.isoformat(datetime.utcnow()),
^^^^^^^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'isoformat'
```
Related to: https://github.com/kernelci/kernelci-pipeline/pull/1277

src/timeout: fix `datetime` related error

---

docker-compose-kcidb.yaml

File logging has stopped working when services started using `kernelci/staging-kernelci:pipeline` image.
Enable it again.
Related to: https://github.com/kernelci/kernelci-pipeline/pull/1265/

send_kcidb: fix file logging

---

src/job_retry.py

Enable job retry service to trigger retry for failed/incomplete build jobs.

Enable build job retry

---

config/jobs-chromeos.yaml

LoadPin ensures that all kernel-loaded files (modules, firmware, etc.) originate from the same filesystem. This prevents modules from loading during testing.
In lava test setup, modules come from the NFS rootfs rather than a verified rootfs. Remove loadpin from the kernel args so modules can be loaded during testing.

config: chromeos: remove loadpin from kernel args

---

config/jobs-chromeos.yaml
config/scheduler-chromeos.yaml

Enable wifi-basic tests for chromiumos tree

config: chromeos: enable wifi-basic tests

---

config/platforms.yaml
config/scheduler.yaml

This PR currently depends on #1267 - it uses changes introduced by that PR. It can be made an independent PR if merging its current parent has to be postponed ~~until the root cause of [the error](https://github.com/kernelci/kernelci-pipeline/pull/1267#issuecomment-3266961592) is found~~.

platforms: Add support for SiFive HiFive Premier P550

---

src/send_kcidb.py

Update KCIDB bridge to only send final retry i.e. job with `retry_counter=3` for failed boot jobs.

Send final retry of failed boot jobs

---

config/jobs-chromeos.yaml

Drop loadpin from wifi-basic-cros-kernel job kernel args.

config: chromeos: wifi: remove loadpin
