kernelci/kernelci-pipeline

- src/runner.py
Move all the code to actually run a test to a separate Runner class
and create a separate temporary directory when running each job so the
generated files don't overwrite each other.
> src/runner.py: add Runner class and use temp directory

- src/trigger.py
> src/trigger.py: Fix pycodestyle indentation error

- .github/workflows/main.yml
- requirements-dev.txt
> github: Create main.yml

- src/tarball.py
Fix the logic buy updating the linux kernel git repo checkout before
running "git describe" in it.
Fixes: 1ff22eb2480e ("src/tarball.py: add to create source tarballs")
> src/tarball.py: update repo before running git describe

- README.md
Fixes https://github.com/kernelci/kernelci-pipeline/issues/17
Add instructions for Linux tarball creation on WSL.
Need to enable case sensitivity for file system on WSL
in order to fix Linux tarball creation.
> README.md: Add section to setup pipeline on WSL

- src/send_kcidb.py
This PR contains a series of small fixes and improvements on top of #22 following issues hit while running it on staging.
> kcidb: fixes and improvements

- config/kernelci.conf
- src/runner.py
- src/tarball.py
- src/trigger.py
Move default command-line argument values to kernelci.conf so they can be overridden by different pipeline instances.
> Move default arguments to kernelci.conf

- src/test_report.py
Below PRs needs to be merged first : 
https://github.com/kernelci/kernelci-api/pull/121 and https://github.com/kernelci/kernelci-core/pull/1052
Use a function to get root node to generate test report.
> src/test_report.py: use 'get_root_node' function

- README.md
Add links to https://kernelci.org/docs for the
setup and usage instructions and remove duplicate
information from the file.
> README.md: Use documentation from kernelci.org/docs 

- config/logger.conf
- src/logger.py
- src/notifier.py
- src/runner.py
- src/send_kcidb.py
- src/tarball.py
- src/test_report.py
- src/trigger.py
Define handler, formatter, and other configuration
options for root and other loggers for client scripts.
> Integrate 'logging' module

- config/pipeline.yaml
- src/runner.py
Add definitions for a Kubernetes lab and device type to run Python scripts in Kubernetes.
> T34238 Add kubernetes to pipeline.yaml

- src/logger.py
- src/notifier.py
- src/runner.py
- src/send_kcidb.py
- src/tarball.py
- src/test_report.py
- src/trigger.py
src/logger.py: Refactor logger class
src/*.py: Remove global 'logger' variable
> T34953 Refactor logger

- src/runner.py
Add `--node-id` and `--git-commit` command line arguments to `runner.py` to specify a node or revision manually rather than listen for pub/sub events.
Depends on #45
> Add options for manual test runs rather than pub/sub

- src/runner.py
Switch to Kubernetes for running the check-describe Python PoC test script.
Depends on #50 and #57
> T34238 use k8s lab

- config/kernelci.conf
- config/pipeline.yaml
- src/test_report.py
Create and send e-mails reports in the new Kernel CI pipeline.
> Create and send e-mails

- src/notifier.py
Add timeout status for Node objects.
> notifier.py: add 'Timeout' status

- src/notifier.py
- src/runner.py
- src/send_kcidb.py
- src/tarball.py
Depends on https://github.com/kernelci/kernelci-api/pull/155 and https://github.com/kernelci/kernelci-pipeline/pull/62
Add Node.result and change the value of Node.status for the tarball node based on the new Node model schema.
> T36372 Change nodes with new schema

- config/kernelci.conf
- src/runner.py
runner.py: move '_job_tmp_dirs' to RunnerLoop class
kernelci.conf: add 'target' to runner configurations
unner.py: drop unused 'import json'
> T35896 Extend runner refactoring

- config/kernelci.conf
- src/test_report.py
Fix the SMTP server config with sample values in comments.
> Fix up SMTP config

- src/test_report.py
test_report: print only email body to logs
test_report: change to appropriate log level
test_report: fix a typo in log message
> T36539 Test report logs cleanup

- config/kernelci.conf
- config/reports/test-report.jinja2
- docker-compose.yaml
- src/complete_hack.py
- src/notifier.py
- src/runner.py
- src/send_kcidb.py
- src/tarball.py
- src/test_report.py
Replaces #72 with additional fixes to get email reports sent again.
> Fix email reports and complete tarball nodes (#72 fixup)

- config/pipeline.yaml
- config/runtime/kunit.jinja2
Add a template and YAML config entry for running KUnit.
> Add kunit test plan

- src/test_report.py
Simplify the `email_report.py` code in preparation for adding support for results from test groups:
* Remove unnecessary exception handling
* Use `_` for all private methods
* Use object attributes when applicable
* Always print the email content on stdout
> Clean up email report script

- config/runtime/fstests.jinja2
Build the kernel for `kvm-xfstests`.
> src/fstests/runner: add a step to build kernel

- src/notifier.py
Use the new Node state names and tweak formatting accordingly.
> src/notifier: update output with new state names

- src/complete_hack.py
- src/runner.py
- src/tarball.py
- src/test_report.py
- src/trigger.py
Drop the concept of a `tarball` node and add the source tarball URL as an artifact of the `checkout` node.  Update the trigger, tarball, runner, test_report and complete_hack scripts accordingly.
> Merge tarball node into checkout node

- src/tarball.py
Send an update to the checkout node only once with the version
information and the tarball URL and state set to "available" rather
than doing this in two steps.  This was useful previously when there
was a separate tarball node.
Depends on #132
> tarball.py: update checkout node only once

- src/fstests/fstests.jinja2
- Update the run function to return a valid node and implement the submit function to submit the results to the API.
> src/fstests: Submit fstests results to api

- src/test_report.py
Add a "single" command for generating a single report from a given checkout node id.  The report can be dumped to stdout and/or sent over SMTP.
Update the implementation to reuse the common code between these 2 commands accordingly.
> src/test_report.py: add command for generating report by hand

- src/fstests/README.md
Once all the implementation is in place to run fstests, update README with any extra information about how to set this up.
Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>
> src/fstests: update documentation

- src/fstests/runner.py
Sync this code with kernelci-core (commit
186635335aa2bfc3429eaece83de56f1455dd213)
Signed-off-by: Ricardo Cañuelo <ricardo.canuelo@collabora.com>
> src/fstests: update templates_paths parameter name

- config/kernelci.conf
- config/logger.conf
- docker-compose.yaml
- src/tarball.py
- src/timeout.py
Depends on https://github.com/kernelci/kernelci-api/pull/183
src/tarball: Update checkout node with holdoff timestamp when the node state is changed to `available`.
src/timeout: Implement a method to change the state of `available` node based on holdoff. Set node state to `done` if holdoff is expired and all child nodes are completed. Set node state to `closing` if holdoff is expired and at least one of the child nodes is incomplete.
> src/timeout: Implement method to change state of available node based on holdoff

- config/reports/test-report.jinja2
- src/test_report.py
Fixes https://github.com/kernelci/kernelci-pipeline/issues/168
> T38685 src/test_report: prevent empty test report generation

- src/notifier.py
- src/runner.py
- src/tarball.py
- src/test_report.py
- src/timeout.py
- src/trigger.py
Refactor all the services to align their implementation using a class with common members and similar patterns for the main loop etc.  This should help consolidate things as a follow-up with a base class to group the common part and simplify each implementation.
> Refactor class-based implementation of all the services

- src/base.py
- src/notifier.py
- src/runner.py
- src/tarball.py
- src/trigger.py
Add a base `Service` class and start refactoring services to use it.  This is to consolidate the code and avoid duplicating the same pattern in each service.
Depends on #172
> Add base Service class

- src/trigger.py
Use the 'poll_period' and 'force' command line arguments in the
._setup() method to add them to the context data rather than in the
Trigger() constructor.  This puts back the original logic in the code
so that the service object may be reused independently of the command
line arguments.
Fixes: d4b8bfe ("src/trigger.py: add Trigger class and refactor loop")
Depends on #175
> src/trigger.py: use args in context rather than in constructor

- config/kernelci.conf
- config/logger.conf
- docker-compose.yaml
- src/regression_tracker.py
Depends on https://github.com/kernelci/kernelci-api/pull/151,  https://github.com/kernelci/kernelci-api/pull/163, https://github.com/kernelci/kernelci-core/pull/1247, https://github.com/kernelci/kernelci-core/pull/1275, and https://github.com/kernelci/kernelci-core/pull/1430
Add a client script that listens to the node created and updated events and tracks regressions for nodes.
> T35922 Regression tracker script

- config/kernelci.conf
- src/send_kcidb.py
Refactor KCIDB bridge service for the below improvements:
- use `Service` as a base class
- code refactoring by defining methods
- define configurations options for KCIDB project id and topic
> T39195 Refactor kcidb bridge service

- src/fstests/runner.py
- src/runner.py
Depends on https://github.com/kernelci/kernelci-api/pull/191
POST node request can result in HTTPException if the node's parent is not in `available` state while creating a child.
Need to handle the exception in methods for creating nodes and scheduling jobs in the runner script.
> T38154 runner: Handle exceptions when creating jobs

- src/regression_tracker.py
Refactor `regressio_tracker.py` using the `Service` as a base class.
> T39232 Refactor regression tracker script

- src/timeout.py
Depends on https://github.com/kernelci/kernelci-core/pull/1587
Fixes https://github.com/kernelci/kernelci-pipeline/issues/191
Instead of statically defining pending node states, use `db.node_states` enum to get the states from `kernelci-core`.
This will make it easier to use the node states across all the client services.
> T39494 src/timeout: use `db.get_node_states`

- src/base.py
- src/job.py
- src/notifier.py
- src/regression_tracker.py
- src/runner.py
- src/send_kcidb.py
- src/tarball.py
- src/test_report.py
- src/timeout.py
- src/trigger.py
Rework all the services to use the new `API` and `APIHelper` classes from `kernelci-core`.
> Rework services with new `API` and `APIHelper` classes

- src/trigger.py
Handle exceptions in the trigger service loop when sending nodes to the API.
> Handle trigger exceptions

- src/job.py
- src/runner.py
Consolidate long log messages into a single one and add one with every job that gets scheduled to help debugging on staging.
> src/{runner,job}.py: tweak log messages

- config/pipeline.yaml
- config/runtime/kunit.jinja2
Add a `kunit-x86_64` test plan to build and run KUnit on x86_64.
Depends on https://github.com/kernelci/kernelci-core/pull/1838
> Add `kunit-x86_64` test plan

- config/pipeline.yaml
- config/runtime/kbuild.jinja2
- docker-compose.yaml
Add an initial `kbuild` test plan to build `x86_64_defconfig` in Kubernetes with gcc-10 and upload the artifacts to storage.
> Add initial `kbuild` test plan

- .gitignore
- config/pipeline.yaml
- docker-compose.yaml
- src/runner.py
Add a `docker` device type and a `runner-docker` service to run `kunit` in a local Docker container.
> Add Docker runner service

- src/runner.py
Now that we have "kci job" to generate a job and submit it, drop the "run" command used to run a single job in the runner service so it can be simplified as part of the core rework.
> src/runner.py: drop single run command

- config/pipeline.yaml
- docker-compose.yaml
- src/job.py
- src/runner.py
Rewrite the test plans in `pipeline.yaml` as "jobs" and update the runner service implementation accordingly.
> Use new pipeline job config

- src/regression_tracker.py
When runner submits a hierarchy of nodes at a single shot, the API will publish event just for parent node.
In that case, the parent node can have "pass" result, even if one of its child has failed.
Tweak regression tracker to listen to events when "checkout" node reaches to "done" state instead of getting nodes with just "fail" result.
That way we can traverse through all the child nodes using the checkout node and check for regressions.
Fixes #36
> T42060 src/regression_tracker: check for regression in all child nodes

- src/timeout.py
In order to avoid hitting issues with API permissions when updating nodes that aren't owned by the current user, even with an admin API token, ignore nodes that have a different owner to the current user running the timeout service.
This is most likely a temporary measure until API permissions have been fixed as the timeout service should in principle be able to transition all nodes from all users.
> src/timeout: only update nodes owned by the current user

- config/pipeline.yaml
Update SAS token to read Azure files after ZDI-CAN-22317.
> pipeline.yaml: Update SAS token for reading files

- src/monitor.py
- src/regression_tracker.py
- src/scheduler.py
- src/send_kcidb.py
- src/tarball.py
- src/test_report.py
- src/timeout.py
- src/trigger.py
Fixes https://github.com/kernelci/kernelci-core/issues/2120
As discussed, if --yaml-config set - it will load config files from specified directory, which allows us to make more complex configuration with multiple files.
> config: Respect --yaml-config option, if it is set

- kube/aks/restart.sh
Add a basic restart.sh script to restart all the pipeline pods.
> kube/aks: add restart.sh to restart all the pods

- src/lava_callback.py
- src/regression_tracker.py
- src/scheduler.py
- src/tarball.py
- src/test_report.py
- src/timeout.py
- src/trigger.py
Update all the pipeline services to use the new API.Node bindings class for all node-related operations.
> src: update all services to use API.Node class

- src/timeout.py
- src/trigger.py
Use the new API.User bindings class in all services for user-related operations.
> src: update all services to use new API.User class

- config/runtime/kbuild.jinja2
Use kbuild library from kernelci-core to simplify python code
in jinja template.
> kbuild.jinja2: Simplify kbuild template by using KBuild module

- config/runtime/kver.jinja2
- src/monitor.py
- src/regression_tracker.py
- src/send_kcidb.py
- src/tarball.py
- src/test_report.py
- src/trigger.py
Companion PR to https://github.com/kernelci/kernelci-api/pull/395
Also related: https://github.com/kernelci/kernelci-core/pull/2224
> Changes to sync to the new node models

- config/reports/test-report.jinja2
- src/test_report.py
Fixes https://github.com/kernelci/kernelci-pipeline/issues/385
Created on top of https://github.com/kernelci/kernelci-pipeline/pull/384
> Fix test report subject

- src/lava_callback.py
From security POV authentication should be done before anything. Then, we cannot use log.txt in new data model, dot in key means nested attribute in mongodb.
> lava_callback: Fix artifact name and move auth at top

- config/pipeline.yaml
Partner of https://github.com/kernelci/kernelci-core/pull/2303 (merge after that one)
> config/pipeline.yaml: add "kind" to job definitions

- config/pipeline.yaml
- config/runtime/kbuild.jinja2
Add arm64 Chromebook to build as test of cross-compilation support.
> pipeline.yaml: Add arm64 chromebook builds

- src/scheduler.py
Depends on https://github.com/kernelci/kernelci-core/pull/2315/
Fixes https://github.com/kernelci/kernelci-core/issues/2311
Store job ID received from runtime to `Node.data.job_id` field. The field has been introduced to store job details that can be used for further debugging purposes.
> src/scheduler: add `job_id` field to node

- config/pipeline.yaml
- docker-compose.yaml
Enable more k8s clusters to distribute kernel builds.
> pipeline.yaml: Add more k8s clusters

- config/pipeline.yaml
Enable more architectures builds to see what is missing in kbuild.
> pipeline.yaml: Enable more architectures

- config/pipeline.yaml
Add all stable-rc trees for testing.
> pipeline.yaml: Add all stable trees

- .gitignore
- config/runtime/kbuild.jinja2
This PR includes 2 small fixes that otherwise annoy me during development:
* ensure `.pyc` files are ignored by git
* drop unneeded global variables to avoid confusion during debug
> Minor improvements

- config/pipeline.yaml
- config/runtime/kselftest.jinja2
Depends on: https://github.com/kernelci/kernelci-core/pull/2417
Please see commit message for detailed description of the purpose of this PR.
> config: add initial template for kselftests

- config/pipeline.yaml
- config/runtime/kbuild.jinja2
Add dtbs_check as parameter for kbuild
> kbuild.jinja2: Add dtbs_check parameter

- src/regression_tracker.py
Depends on https://github.com/kernelci/kernelci-core/pull/2432
> src/regression_tracker: add config_full to queries and regression objects

- src/tarball.py
As we experienced several times git directory corruption, and it seems repeating issue, we need to implement failover mechanism, such as clean git directory and retry.
> tarball: Implement gentle clean/retry mechanism

- src/scheduler.py
In most situations, jobs need artifacts generated by their parent. As those ar no longer automatically propagated, we need to import them when needed.
> scheduler: import artifacts from parent node before running job

- src/scheduler.py
Counterpart to and depends on https://github.com/kernelci/kernelci-core/pull/2438
> Implement param formatting in scheduler

- src/regression_tracker.py
Add all the failed node log artifacts as regression artifacts.
> src/regression_tracker: add failed node logs to regression

- src/regression_tracker.py
Companion to https://github.com/kernelci/kernelci-core/pull/2440 but not dependent on it.
> src/regression_tracker: collect error code and msg from failed node

- config/pipeline.yaml
Reason of not triggering job that rules was not properly set.
> pipeline.yaml: Fix dtbs_check rules to trigger test

- config/result-summary.yaml
- config/result_summary_templates/stable-rc-boot-failures.jinja2
- config/result_summary_templates/stable-rc-boot-regressions.jinja2
- config/result_summary_templates/stable-rc-build-failures.jinja2
- config/result_summary_templates/stable-rc-build-regressions.jinja2
Additional pair of presets and templates to check for failures instead of regressions.
> result_summary: stable-rc build and boot presets for failures

- config/pipeline.yaml
Enable for test one clang build
> pipeline.yaml: enable one clang build

- src/scheduler.py
In some cases, for example rendering error, we might have job definition empty or None, then generate error, but dont crash scheduler.
> scheduler: handle without crash empty job definition

- config/platforms-chromeos.yaml
- config/scheduler-chromeos.yaml
Update volteer devices according lab availability
> configs/: Update volteer device

- src/lava_callback.py
As storage space in cloud and egress have high costs, better to compress potentially large files.
> lava_callback: Compress the log files to save storage space

- .github/workflows/main.yml
- tests/validate_yaml.py
Add yaml load to figure out earlier issues with yaml
> tests: Add basic yaml validation

- src/timeout.py
Fixes https://github.com/kernelci/kernelci-pipeline/issues/555
`TimeoutService._get_child_nodes_recursive` is used to get pending child nodes recursively for closing and timed-out nodes. It overwrites the result while being called recursively. Fix the method to make it work properly.
> src/timeout: fix method to get child nodes recursively

- kube/aks/ingress.yaml
- kube/aks/lava-callback.yaml
- kube/aks/monitor.yaml
- kube/aks/nodehandlers.yaml
- kube/aks/scheduler-k8s.yaml
- kube/aks/scheduler-lava.yaml
- kube/aks/tarball.yaml
- kube/aks/trigger.yaml
Fixes in yaml files for k8s production deployment.
> k8s: Lot of deployment tested fixes

- src/timeout.py
Fixes https://github.com/kernelci/kernelci-pipeline/issues/548
Created on top of https://github.com/kernelci/kernelci-pipeline/pull/556 to avoid merge conflicts.
> Fix `checkout` node transition to `done` state

- src/lava_callback.py
This was supposed to be dropped before merging.
> Revert "DONOTMERGE lava_callback: add debug statements"

- src/tarball.py
We often need not ToT, but specific commit, implement this.
> tarball: Implement checkout for specific commit

- config/result-summary.yaml
https://github.com/kernelci/kernelci-pipeline/pull/586 is the pre-requisite for this PR.
> result_summary presets: add presetes for fluster test

- config/jobs-chromeos.yaml
- config/pipeline.yaml
- config/scheduler-chromeos.yaml
Please look at the commit description for individual descriptions of patches.
> Add all supported fluster tests to run on all the boards

- config/pipeline.yaml
- config/runtime/kbuild.jinja2
Add more build variants for stable-rc tree to match legacy system.
> pipeline.yaml: Add stable-rc build variants

- config/result_summary_templates/generic-regressions.html.jinja2
- config/result_summary_templates/generic-test-results.html.jinja2
- config/traces_config.yaml
- src/result_summary/utils.py
Classify errors according to patterns in the logs.
~~TODO: classify based on the concatenated logs instead of per log file~~
~~TODO: remove traces_config global var from utils~~
> result_summary: add error classification

- config/pipeline.yaml
Enable all android branches from the legacy system
> config/pipeline: enable android branches from legacy

- src/trigger.py
As we need to restrict list of running kernels on staging, we need to add option allowing that.
Also it will be good to exclude staging kernels from production kernel list.
So in case of staging we need to run kernels only from tree "kernelci"
and sometimes something else, for example "mediatek".
Option will look like:
--trees kernelci,mediatek
or
--trees kernelci
On production we need to exclude trees kernelci and buggytree:
--trees !kernelci,buggytree
or just kernelci:
--trees !kernelci
Purpose of this option is that our compiling capacity is limited,
and right now staging and production both compiling very large set
of kernels, we need to reduce this amount to drop costs.
> trigger: Add exclude/include tree list for trigger

- src/lava_callback.py
Most likely problems lays in threading of flask, and possibly callbacks are getting mixed. This commit attempts to introduce several countermeasures against that.
> lava_callback: Sometimes we get totally invalid log file uploaded

- doc/_index.md
- doc/connecting-lab.md
- doc/developer-documentation.md
- doc/pipeline-details.md
Related to https://github.com/kernelci/kernelci-project/issues/338
> Re-structure pipeline doc

- config/jobs-chromeos.yaml
- config/pipeline.yaml
- src/send_kcidb.py
Alternative to https://github.com/kernelci/kernelci-pipeline/pull/517
Related to https://github.com/kernelci/kcidb/issues/338
Depends on https://github.com/kernelci/kernelci-core/pull/2537, https://github.com/kernelci/kernelci-core/pull/2550
> Submit data to KCIDB

- config/jobs-chromeos.yaml
- config/pipeline.yaml
- config/runtime/kunit.jinja2
Depends on https://github.com/kernelci/kernelci-core/pull/2571
> Re-structure test hierarchy with `kind=job` for test suites

- src/send_kcidb.py
Depends on https://github.com/kernelci/kernelci-pipeline/pull/639
Update evaluation of KCIDB status from KCI result.
> Update KCIDB status mapping

- kube/aks/pipeline-kcidb.yaml
We need file that will manage deployment of kcidb bridge in kubernetes production deployment.
> aks: Add kubernetes kcidb deployment

- kube/aks/lava-callback.yaml
- kube/aks/monitor.yaml
- kube/aks/nodehandlers.yaml
- kube/aks/scheduler-k8s.yaml
- kube/aks/scheduler-lava.yaml
- kube/aks/tarball.yaml
- kube/aks/trigger.yaml
1)Update memory limit, as working with linux sources might require 3Gbyte of RAM. 
2)Update config file path
3)Add callback environment variable
4)Update image reference to fresh one
> k8s/aks: Update deployment files

- config/pipeline.yaml
- config/runtime/preempt-rt.jinja2
- config/runtime/rt-tests.jinja2
- config/scheduler-chromeos.yaml
https://github.com/kernelci/kernelci-core/pull/2578 is a prerequisite of this PR.
I've included for you the description in individual commits.
> Enable rt-tests

- tests/validate_yaml.py
Add more validation to config files of mandatory parameters.
> validate_yaml.py: Jobs are required to have template parameter

- tests/validate_yaml.py
Add basic validation, each job must have kind parameter
> validate_yaml.py: Add more job validations

- .github/workflows/main.yml
As suggested in similar actions: https://github.com/actions/labeler
> workflows: Run pull_request_target for differnt context

- config/pipeline.yaml
The request for this addition can be found: https://github.com/kernelci/kernelci-pipeline/issues/714
> config: pipeline: enable 6.9.y stable-rc

- config/pipeline.yaml
Related to: https://github.com/kernelci/kernelci-pipeline/pull/716
Closes: https://github.com/kernelci/kernelci-pipeline/issues/714
> config: pipeline: Enable linux-6.10.y branch

- doc/developer-documentation.md
Closes https://github.com/kernelci/kernelci-pipeline/issues/650
Explain KernelCI test hierarchy structure and results semantics.
> doc/developer-documentation: test hierarchy and result evaluation

- config/pipeline.yaml
(Added description to individual commmits)
> Enable builds of arnd, amlogic and ardb trees

- docker/lava-callback/requirements.txt
- src/lava_callback.py
- tools/jwt_generator.py
- tools/kci-maintainer
Add call to create custom checkout node (manually specified commit).
> lava_callback: Add API call to pipeline

- config/pipeline.yaml
- config/runtime/ltp.jinja2
- config/scheduler-chromeos.yaml
https://github.com/kernelci/kernelci-core/pull/2620 is prerequisite for this PR.
> Enable LTP in New KernelCI

- src/lava_callback.py
- tools/jwt_generator.py
- tools/kci-maintainer
@pawiecz had several suggestions that i amended, but by mistake i amended workflow patch, which i dropped later. Returning them back.
> pipeline/api: tools: Add changes that was lost due mistake

- docker-compose-kcidb.yaml
- docker-compose-lava.yaml
- docker-compose.yaml
Restart pipeline container when it exists with an error using `restart` policy.
> Auto restart services on failure

- config/pipeline.yaml
(see individual commits' description for information)
> Enable efi, clk and peterz trees

- config/pipeline.yaml
- config/scheduler-chromeos.yaml
- src/lava_callback.py
- src/patchset.py
- tools/jwt_generator.py
- tools/kci-maintainer
Patchset initial implementation to apply patch to existing checkout node.
> feature(api): Add patchset endpoint

- src/lava_callback.py
We had leftovers from flask that was returning invalid data, when any API calls was sent. Now we return proper JSON.
> fix(lava_callback): Fix all return codes/content

- config/pipeline.yaml
- config/platforms-chromeos.yaml
- tools/extract_compatible.py
Add new tool for devices using DTB, to assist with compatible field.
Also update config files accordingly.
> feat(extract_compatible.py): Add new tool to extract "compatible" field

- src/scheduler.py
```
[ERROR] Traceback (most recent call last):
File "/home/kernelci/pipeline/base.py", line 69, in run
status = self._run(context)
^^^^^^^^^^^^^^^^^^
File "/home/kernelci/./pipeline/scheduler.py", line 197, in _run
self._run_job(job, runtime, platform, input_node)
File "/home/kernelci/./pipeline/scheduler.py", line 120, in _run_job
data = runtime.generate(job, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kernelci/runtime/lava.py", line 303, in generate
return yaml.dump(yaml.load(rendered, Loader=yaml.CLoader))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
return loader.get_single_data()
^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> fix(scheduler): Don't crash if runtime.generate failed

- src/lava_callback.py
Turned out job validation is not working, fixing it.
> fix(lava_callback): Fix job name validation

- tools/kci-maintainer
Often with HTTP error code we receive helpful body message, it will be good to show it.
> kci-maintainer: Improve tool error readability

- config/pipeline.yaml
Enable the following trees:
- agross
- khilman
- kselftest
- mainline
> Enable new trees

- config/pipeline.yaml
Close https://github.com/kernelci/kernelci-pipeline/issues/776
> Enable next and riscv trees

- src/lava_callback.py
- src/trigger.py
Add treeid support to pipeline services
> Treeid support

- config/jobs-chromeos.yaml
(Please find description in individual commits)
> config: jobs-chromeos: Disable tast tests

- tools/kci-maintainer
- tools/kci-maintainer.md
Add for convinience new option to retrieve latest commit automatically.
> feat(option: latest-commit): Add option --latest-commit

- config/pipeline.yaml
I have taken over maintainership of OMAP platforms from Tony, so move this tree to mine.
> config/pipeline: update git tree for omap

- src/send_kcidb.py
- src/trigger.py
Set `user:<user-email>` when pipeline instance is running with other user than the `staging` pipeline.
> src/trigger: set `submitter` field for pipeline

- config/scheduler-chromeos.yaml
Adjust list of platforms according to requirements.
> fix(fluster-chromeos): Adjust platforms running fluster tests

- src/scheduler.py
Add additional messages to help distinct between two places where particular error code might be generated.
> feat(errors): Improve error output

- doc/developer-documentation.md
Closes https://github.com/kernelci/kernelci-pipeline/issues/543
Explain `checkout` node result evaluation by pipeline services.
> doc/developer-documentation: checkout result evaluation

- src/lava_callback.py
We need to filter submissions also by platform to reduce load and make test results more precise.
> feat(lava_callback.py): Add platformfilter parameter

- config/runtime/kbuild.jinja2
Add kselftest option to kbuild parameters.
> feat(kbuild.jinja2): Add kselftest option

- config/pipeline.yaml
> fix(pipeline.yaml): Fix public access token expiration

- config/jobs-chromeos.yaml
- config/pipeline.yaml
- src/scheduler.py
This commit depends on PR https://github.com/kernelci/kernelci-core/pull/2705
> fix(docker/k8s): Fix image names

- config/pipeline.yaml
As per request from Todd Kjos, adding android16-6.12 branch
> add(pipeline.yaml): android16-6.12 branch

- config/pipeline.yaml
- kube/aks/tarball.yaml
K8S resource increase based on observation. Also fix risc-v typo.
> Fix typo and increase k8s resource allocation

- config/kernelci.toml
Add a bit documentation/comments to toml file.
> feat(toml): Add a bit of comments for toml config

- tools/example_api_pubsub.py
Add very simple code to show how pubsub works and users can receive events.
> feat(tools): Add example_api_pubsub.py

- tools/example_api_events.py
Provide example how to use new events endpoint.
> feat(example_api_events.py): Add example for new events endpoint

- config/kernelci.toml
- src/logspec/logspec/__init__.py
- src/logspec/logspec/errors/error.py
- src/logspec/logspec/errors/kbuild.py
- src/logspec/logspec/errors/linux_kernel.py
- src/logspec/logspec/errors/test.py
- src/logspec/logspec/main.py
- src/logspec/logspec/parser_classes.py
- src/logspec/logspec/parser_defs.yaml
- src/logspec/logspec/parser_loader.py
- src/logspec/logspec/states/chromebook_boot.py
- src/logspec/logspec/states/generic_boot.py
- src/logspec/logspec/states/kbuild.py
- src/logspec/logspec/states/linux_kernel.py
- src/logspec/logspec/states/test_baseline.py
- src/logspec/logspec/transition_functions/common.py
- src/logspec/logspec/transition_functions/linux.py
- src/logspec/logspec/utils/defs.py
- src/logspec/logspec/utils/linux_kernel_errors.py
- src/logspec/logspec/utils/test_baseline_errors.py
- src/logspec/logspec/version.py
- src/logspec/logspec_api.py
- src/send_kcidb.py
Create KCIDB issues and incidents using `logspec` tool.
> Integrate `logspec` tool

- src/logspec/logspec_api.py
Fix version field name for existing KCIDB issue.
> src/logspec: fix version field for KCIDB issue

- config/pipeline.yaml
Close https://github.com/kernelci/kernelci-pipeline/issues/903
Signed-off-by: Muhammad Usama Anjum <usama.anjum@collabora.com>
> config: pipeline: Enable v6.12 stable-rc branch

- doc/config-reference.md
Add documentation for amazing "rules" feature developed by Arnaud. This feature allows us to filter jobs execution.
> feat(doc/config): Add documentation for rules

- config/pipeline.yaml
- Some branches have disappeared. Remove those branches.
- Some branches have been renamed.
There was for-kernelci branch present in peterz's tree which has disappeared. I'm replacing some other branch for now until we get a reply from him.
Close: https://github.com/kernelci/kernelci-pipeline/issues/888
> config: pipeline: Fix failures caused by unsuccessful checkouts

- src/send_kcidb.py
Closes https://github.com/kernelci/kernelci-pipeline/issues/910
Fetch available LAVA runtimes dynamically instead of relying on a static lava labs mapping dictionary.
> src/send_kcidb: get lava labs from config

- src/send_kcidb.py
Disable timed-out checkout, build, job, and test nodes submission to KCIDB for the time being.
This needs to be tweaked when maestro has job retry logic in place.
> src/send_kcidb: don't send timed-out nodes to KCIDB

- src/trigger.py
As we have limited query language, count also incomplete nodes. If particular commit nodes are all incomplete - force checkout again, as checkout was never completed (which happen quite often).
> fix(trigger.py): Trigger should ignore incomplete nodes

- src/send_kcidb.py
It seems due LAVA details incomplete nodes might contain useful data.
> fix(send_kcidb.py): Submit incomplete test nodes

- src/send_kcidb.py
We need more debugging to find missing nodes.
> fix(send_kcidb.py): Add extended log for kcidb bridge

- src/send_kcidb.py
We might have hiccups we notice too late, so increase time window to reprocess data.
> upd(send_kcidb.py): Update reprocess time window to 4 days

- src/send_kcidb.py
1)Set node as processed even if it is not matching requirements for kcidb. 2)Fix wrong search parameters.
> fix(send_kcidb.py): Few fixes

- src/send_kcidb.py
Processing nodes and search for new one by one is too slow, kcidb-bridge jsut cannot keep up with production rate. Let's try to implement batching.
> feat(send_kcidb.py): Implement batch processing

- src/send_kcidb.py
Submitting node one by one seems unproductive and slow as we are depenting on submission RTT, which is way slower than we generate nodes.
> feat(send_kcidb.py): Implement batched submissions

- src/kernelci_pipeline/logspec_api.py
- src/send_kcidb.py
1)Implement file:// schema in logspec_api
2)Implement log file caching locally to reduce storage
call delays and reduce egress costs
3)Caching of excerpt logs to reduce storage retrievals
4)Caching of nodes to reduce API calls
5)Requests batching with fallback in number in case
submission size is too big.
This is emergency update, as we have performance issue,
so everything is crammed into single commit.
> fix(send_kcidb.py): Set flag by bulk operation

- src/kernelci_pipeline/logspec_api.py
- src/send_kcidb.py
1)Logfile need to be opened in binary mode.
2)Use local url for incidents artifact everywhere.
3)file cache expire fix
> feat(logspec_api.py): Various cache fixes

- src/send_kcidb.py
We need to have chance to process events.
If last search returned less than max nodes, this means we got
all pending nodes, switch to events mode.
> fix(send_kcidb.py): Tune a bit workaround processing

- config/pipeline.yaml
Test new rootfs with some packages enabled for netdev
> upd(pipeline.yaml): new kselftest rootfs 

- config/pipeline.yaml
We need to add more testing coverage using amd64/x86 platforms.
> feat(pipeline.yaml): Add more x86 platforms to testing

- config/pipeline.yaml
Add new storage, that is already supported by kernelci-core.
> feat(pipeline.yaml): Add new storage definition

- config/pipeline.yaml
Fresh production builds of rootfs, h26forge and kselftest.
> upd(pipeline.yaml): Update rootfs links

- src/send_kcidb.py
- tools/example_api_lab.py
In some situations we have failures that are invible from logs. We need better logs.
>  feat(example_api_lab.py): Add example for labs how to submit result to Maestro

- src/send_kcidb.py
We need to be able to other users in API, to process events and send to kcidb.
> feat(send_kcidb.py): Add promisc flag to subscribe_filters

- config/pipeline.yaml
We want to compare the stable-rc tests with the latest stable releases. So let's have the stable tests here too.
Also, I am sure people want to see stable results in KernelCI. :)
Next step is to match the same testing for both stable-rc and stable.
> config: pipeline: add all stable branches

- config/pipeline.yaml
- config/pipeline.yaml: Define symbolic names for platform sets in my labs
- config/pipeline.yaml: Run DT selftests on the boards in my lab
> Enable DT selftests in my lab

- config/jobs-chromeos.yaml
- config/pipeline.yaml
We need to update list of tests being run to match stable to stable-rc trees.
> upd(*.yaml): Run stable tree tests same as stable-rc

- config/pipeline.yaml
Add padovan tree for regression tracking and features testing.
> upd(pipeline.yaml): Add padovan tree for testing

- src/send_kcidb.py
We are not ready for the flood of issues being created by this code. Let's keep it disabled for the time being.
> src/send_kcidb: Disable kselftest issue creation

- kube/aks/lava-callback.yaml
Due addition of base module we need to change work directory.
> upd(kubernetes): Fix work directory

- config/pipeline.yaml
- config/runtime/nipa-update.jinja2
To handle NIPA update, after test completion we need to execute nipa-update script.
> feat(nipa-update): Add to pipeline new kind of executor for NIPA

- src/base.py
- src/trigger.py
Various fixes for NIPA reliability
> Fixes misc trigger

- config/platforms.yaml
- config/scheduler.yaml
Basic enablement for core features of the board which I've added to my
lab.
> config: Enable Raspberry Pi 3B+ in my lab

- config/jobs-chromeos.yaml
- config/scheduler-chromeos.yaml
> Drop Tast Debian jobs

- config/jobs.yaml
- config/pipeline.yaml
- config/scheduler.yaml
- kube/aks/scheduler-lava.yaml
My lab was not migrated to new pipeline, lets do it.
> Re-enable lab-clabbe

- config/platforms.yaml
- config/scheduler.yaml
> Enable more boards in lab-clabbe

- tests/validate_yaml.py
We need to verify if platform exist in platforms:
> (tests) Improve config validator

- tests/validate_yaml.py
As it is built on case by case, we check check build config for mandatory options: tree and branch
> (tests/validator) Improve build_configs verification

- config/platforms.yaml
- tests/validate_yaml.py
Fix mistake in platforms.yaml and add basic validation of platforms.
> Improve platforms

- config/trees.yaml
Specify CIP architectures and add 6.12 branch
> Specify CIP architectures and add 6.12 branch

- src/kernelci_pipeline/logspec_api.py
This fields are removed in newest kcidb schema.
> Update fields according to kcidb schema

- doc/config-reference.md
This improvement mostly touch `jobs` section of config file.
> (config-reference-md) Improve config file documentation

- src/lava_callback.py
There is list of issues i kept for a while that is not critical, but preferable to be fixed.
Now adding fixes and improvements to code, at least part of them.
> LAVA callback improvements

- config/jobs.yaml
- config/scheduler.yaml
Yet another small, mostly software only suite.
> config: Add ptrace selftests

- config/jobs.yaml
- config/scheduler.yaml
Another small, software only test.
> config: Enable kcmp selftests

- config/jobs.yaml
- config/scheduler.yaml
Another very small software only selftest.
> config: Enable acct selftests

- config/jobs-cip.yaml
- config/jobs.yaml
> jobs.yaml: Add more coverage for sashal-next

- tests/validate_yaml.py
Various minor improvements and one more config check partially taken from https://github.com/kernelci/kernelci-pipeline/pull/1225
> validate_yaml.py improvements

- src/send_kcidb.py
- src/tarball.py
Fix and improve event filters for subscription retry in `tarball` and `send_kcidb` services.
> Fix re-subscription for pubsub events

- tests/validate_yaml.py
In some cases by mistake it is possible that platform can be set in kbuild, which will cause build job to fail. Also at current moment kbuild support only kubernetes and docker.
> validate_yaml.py: Improve validation of kbuild jobs

- src/send_kcidb.py
Do not send all incomplete jobs and wait for the final retry to be submitted to KCIDB.
> Only send final retry of incomplete jobs
